objects/Account.object
<CustomObject><fields>
        <fullName>Academic_Program_Type__c</fullName>
        <label>Academic Program Type</label>
        <picklist>
            <picklistValues>
                <fullName>Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minor</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Current_Term__c</fullName>
        <label>Current Term</label>
        <length>255</length>
        <type>Text</type>
    </fields><compactLayoutAssignment>hed__HEDA_Account_Compact_Layout</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>Private</sharingModel></CustomObject>

objects/hed__Course__c.object
<CustomObject><fields>
        <fullName>hed__Course_ID__c</fullName>
        <label>Course ID</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Course_Number__c</fullName>
        <label>Course Number</label>
        <length>3</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Subject_Name__c</fullName>
        <description>The full name of a subject related to a course.</description>
        <label>Subject Name</label>
        <length>175</length>
        <type>Text</type>
    </fields><fields>
        <fullName>hed__Account__c</fullName>
        <label>Department</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Course_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Academic course that a Department or School (the degree-granting Account type for the University) offers.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Course</label><nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Courses</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/hed__Course_Offering__c.object
<CustomObject><fields>
        <fullName>LWC_Tutor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LWC Tutor</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Current_Term__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Supports Current Course Offering Report functionality.</description>
        <label>Current Term</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>hed__Term__c</fullName>
        <label>Term</label>
        <referenceTo>hed__Term__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>hed__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>hed__End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>hed__Course__c</fullName>
        <label>Course</label>
        <referenceTo>hed__Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Course_Offering_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Joins Courses and Terms to contain information related to a single occurrence of a course.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Course Offering</label><nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField><pluralLabel>Course Offerings</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/hed__Term__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>hed__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>hed__End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>hed__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Terms</relationshipLabel>
        <relationshipName>Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Term_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Unit of time in which academic activities are taking place.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Term</label><nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Terms</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/USF_CourseConfiguratorTest.cls
@isTest(seeAllData=false)
public class USF_CourseConfiguratorTest {
    public static String termId = '';
    public static String courseId = '';
    
    public static void insertTestData(){
        //insert account
        Account eduInstitution = new Account();
        eduInstitution.Name = 'University of San Fransisco';
        eduInstitution.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Educational Institution').getRecordTypeId();
        eduInstitution.Current_Term__c = 'Fall 2016';
        insert eduInstitution;
        
        Account parentAcc = new Account();
        parentAcc.Name = 'Economics Department';
        parentAcc.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('University Department').getRecordTypeId();
        insert parentAcc;
        
        Account acc = new Account();
        acc.Name = 'Business Economics';
        acc.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        acc.Parent = parentAcc;
        acc.Academic_Program_Type__c = 'Major';
        insert acc;
        
        //insert a term
        hed__Term__c term1 = new hed__Term__c();
        term1.Name = 'Fall 2016';
        term1.hed__Start_Date__c = System.today() - 1;
        term1.hed__End_Date__c = System.today() + 3;
        term1.hed__Account__c = eduInstitution.Id;
        insert term1;
        termId = term1.Id;
        
        //insert course
        hed__Course__c course1 = new hed__Course__c();
        course1.Name = 'Business of the World';
        course1.hed__Course_ID__c = 'BUS202';
        course1.hed__Account__c = acc.Id;
        course1.Course_Number__c = '201';
        course1.Subject_Name__c = 'Business';
        insert course1;
        courseId = course1.Id;
        
        //insert course offering
        hed__Course_Offering__c courseOffering1 = new hed__Course_Offering__c();
        courseOffering1.Name = 'BE202Fall2016';
        courseOffering1.hed__Term__c = term1.Id;
        courseOffering1.Current_Term__c = true;
        courseOffering1.hed__Course__c = course1.Id;
        courseOffering1.Active__c = true;
        insert courseOffering1;
        
        hed__Course_Offering__c courseOffering2 = new hed__Course_Offering__c();
        courseOffering2.Name = 'BE202Fall2016';
        courseOffering2.hed__Term__c = term1.Id;
        courseOffering2.Current_Term__c = true;
        courseOffering2.hed__Course__c = course1.Id;
        courseOffering2.Active__c = true;
        courseOffering2.LWC_Tutor__c = true;
        insert courseOffering2;
                        
    }
    static testMethod void validateGetTerms(){
        insertTestData();
        Test.startTest();
        USF_CourseConfigrator controller = new USF_CourseConfigrator();
        controller.getTerms();
        Test.stopTest();
    }
    static testMethod void validateGetCampus(){
        insertTestData();
        Test.startTest();
        USF_CourseConfigrator controller = new USF_CourseConfigrator();
        controller.getCampus();
        Test.stopTest();
    }
    static testMethod void validateGetMode(){
        insertTestData();
        Test.startTest();
        USF_CourseConfigrator controller = new USF_CourseConfigrator();
        controller.getMode();
        Test.stopTest();
    }
    static testMethod void validateGetLevel(){
        insertTestData();
        Test.startTest();
        USF_CourseConfigrator controller = new USF_CourseConfigrator();
        controller.getLevel();
        Test.stopTest();
    }
    
    public static void addAllCourses(USF_CourseConfigrator controller){
        if(!controller.courseMap.isEmpty()){
            for(String courseSubjectName : controller.courseMap.keySet()){
                for(USF_CourseConfigrator.courseWrapper wrapper : controller.courseMap.get(courseSubjectName)){
                    wrapper.selected = true;
                }
            }
        }
        controller.addCourses();
    }
    
    public static void removeAllCourses(USF_CourseConfigrator controller){
        if(!controller.courseMap.isEmpty()){
            for(String courseSubjectName : controller.addedCourseMap.keySet()){
                for(USF_CourseConfigrator.courseWrapper wrapper : controller.addedCourseMap.get(courseSubjectName)){
                    wrapper.selected = true;
                }
            }
        }
        controller.removeCourses();
    }
    
    static testMethod void validatePopulateCourses(){
        insertTestData();
        Test.startTest();
        USF_CourseConfigrator controller = new USF_CourseConfigrator();
        controller.populateCourses(termId,'--None--','--None--','--None--','--None--');
        System.debug('addedCourseMap: '+controller.addedCourseMap);
        System.debug('courseMap: '+controller.courseMap);
        addAllCourses(controller);
        removeAllCourses(controller);
        controller.saveCourses();
        controller.termId = termId;
        controller.levels = '--None--';
        controller.offeredtype = '--None--';
        controller.campusid = '--None--';
        controller.types = '--None--';
        
        hed__Course_Offering__c courseOffering1 = new hed__Course_Offering__c();
        courseOffering1.Name = 'BE202Fall2016';
        courseOffering1.hed__Term__c = termId;
        courseOffering1.Current_Term__c = true;
        courseOffering1.hed__Course__c = courseId;
        courseOffering1.Active__c = true;
        insert courseOffering1;
        
        hed__Course_Offering__c courseOffering2 = new hed__Course_Offering__c();
        courseOffering2.Name = 'BE202Fall2016';
        courseOffering2.hed__Term__c = termId;
        courseOffering2.Current_Term__c = true;
        courseOffering2.hed__Course__c = courseId;
        courseOffering2.Active__c = true;
        courseOffering2.LWC_Tutor__c = true;
        insert courseOffering2;
        
        controller.populateCoursesBasedUponTerm();
        removeAllCourses(controller);
        addAllCourses(controller);       
        
        Test.stopTest();
    }
    static testMethod void validateAddingRemovingCourses(){
        insertTestData();
        Test.startTest();
        USF_CourseConfigrator controller = new USF_CourseConfigrator();
        controller.populateCourses(termId,'--None--','--None--','--None--','--None--');
        System.debug('addedCourseMap: '+controller.addedCourseMap);
        System.debug('courseMap: '+controller.courseMap);
        //adding one course
        if(!controller.addedCourseMap.isEmpty()){
            for(String courseSubjectName : controller.addedCourseMap.keySet()){
                for(USF_CourseConfigrator.courseWrapper wrapper : controller.addedCourseMap.get(courseSubjectName)){
                    wrapper.selected = true;
                    break;
                }
            }
        }
        controller.addCourses();
        //removing one course
         if(!controller.courseMap.isEmpty()){
            for(String courseSubjectName : controller.addedCourseMap.keySet()){
                for(USF_CourseConfigrator.courseWrapper wrapper : controller.addedCourseMap.get(courseSubjectName)){
                    wrapper.selected = true;
                    break;
                }
            }
        }
        controller.removeCourses();
        controller.saveCourses();
        Test.stopTest();
    }
}