objects/Account.object
<CustomObject><fields>
        <fullName>BusinessHour__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Business hours to be followed for this account</description>
        <label>Business Hour</label>
        <referenceTo>BusinessHours</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields><compactLayoutAssignment>hed__HEDA_Account_Compact_Layout</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>Private</sharingModel></CustomObject>

objects/App_Config__c.object
<CustomObject><fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <type>TextArea</type>
    </fields><customSettingsType>List</customSettingsType><description>Stores all configurable settings for USF</description><enableFeeds>false</enableFeeds><label>App Config</label><visibility>Public</visibility></CustomObject>

objects/AppointmentContact__c.object
<CustomObject><fields>
        <fullName>AppointmentSlot__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Appointment Slot</label>
        <referenceTo>Counsellor_Availability__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointment_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><fields>
        <fullName>AppointmentType__c</fullName>
        <formula>AppointmentSlot__r.AppointmentType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Appointment Type</label>
        <type>Text</type>
    </fields><fields>
        <fullName>CWID__c</fullName>
        <formula>Contact__r.CWID__c</formula>
        <label>CWID</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Canceled_Date_Time__c</fullName>
        <description>Captures time stamp when the appointment has been cancelled</description>
        <label>Canceled Date/Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointment_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Reason_for_Meeting__c</fullName>
        <label>Appointment Reasons</label>
        <picklist>
            <picklistValues>
                <fullName>Academic Coaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Probation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Concerns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housing / Residence Hall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leave of Absence / Withdrawal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Concerns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major / Minor Exploration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Study Abroad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Student Survey</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Appointments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Notes</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Strike__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Strike</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Appointment</label><nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Appointments</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Case.object
<CustomObject><fields>
        <fullName>CWID__c</fullName>
        <formula>Contact.CWID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CWID</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Course_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>hed__Course_Offering__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Description</fullName>
        
    </fields><fields>
        <fullName>Origin</fullName>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit - Drop in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit - Scheduled Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WebTrack</fullName>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields>
        <fullName>OwnerId</fullName>
        
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Priority</fullName>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Reason</fullName>
        <picklist>
            <picklistValues>
                <fullName>Academic Coaching</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Disqualification</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Form Processing</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Integrity</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Probation</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Appointment Information</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>CMBIT</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Dean's Letter / Tuition Adjustment</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Disability Related Issues</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Disruptive Behavior</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Early Alert</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty/Student Complaint</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty Notification</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Needs</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Grade Appeal / Grade Change</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Graduation</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Homesickness</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Housing / Residence Hall</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Leave of Absence/Withdrawal from USF</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Loss / Grief</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Major / Minor Exploration</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Health</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>New Student Survey</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Referral</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Assistance</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>SOM Waitlist</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Study Abroad</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Substance Abuse</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Underenrolled</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Status</fullName>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
                <closed>false</closed>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <closed>false</closed>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
                <closed>true</closed>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
                <closed>true</closed>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Subject</fullName>
        
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Type</fullName>
        <picklist>
            <picklistValues>
                <fullName>Problem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feature Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Question</fullName>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Contact.object
<CustomObject><fields>
        <fullName>AcademicSuccessCoach__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Academic Success Coach</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notEqual</operation>
                <value>Customer Community User</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>CWID__c</fullName>
        <description>The primary USF ID</description>
        <externalId>true</externalId>
        <label>CWID</label>
        <length>100</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Number_of_Units_in_Current_Term__c</fullName>
        <label>Number of Units in Current Term</label>
        <precision>3</precision>
        <scale>0</scale>
        
        <type>Number</type>
    </fields><fields>
        <fullName>Reason_Withdrawn__c</fullName>
        <label>Reason Withdrawn</label>
        <length>255</length>
        
        <type>Text</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Related to Interaction functionality</description>
        <label>Student</label>
        <type>Checkbox</type>
    </fields><compactLayoutAssignment>hed__HEDA_Contact_Compact_Layout</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Counsellor_Availability__c.object
<CustomObject><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed by Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Appointments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Slot</label><nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Coach Availability Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Slots</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Counselor_Availability_Definition__c.object
<CustomObject><fields>
        <fullName>Coach__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coach</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Availability_Definition</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Repeat__c</fullName>
        <inlineHelpText>Select "Only Once" to create slots for a single day.
Select "Daily" to create slots every day of a specified date range. Do not select specific days.
Select "Weekly" to create slots for selected days of a specified date range. Select the specific days.</inlineHelpText>
        <label>Repeat</label>
        <picklist>
            <picklistValues>
                <fullName>Only Once</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Success_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Center</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Center__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Availability (Center)</relationshipLabel>
        <relationshipName>Availability</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Availability</label><nameField>
        <displayFormat>CAD-{0000}</displayFormat>
        <label>Coach Availability Definition Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Availability</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Read</sharingModel></CustomObject>

objects/hed__Course__c.object
<CustomObject><fields>
        <fullName>hed__Account__c</fullName>
        <label>Department</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Course_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Academic course that a Department or School (the degree-granting Account type for the University) offers.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Course</label><nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Courses</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/hed__Course_Offering__c.object
<CustomObject><fields>
        <fullName>hed__Term__c</fullName>
        <label>Term</label>
        <referenceTo>hed__Term__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>hed__Section_ID__c</fullName>
        <label>Section ID</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>hed__Faculty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Faculty</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Courses_Taught</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>hed__Course__c</fullName>
        <label>Course</label>
        <referenceTo>hed__Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Course_Offering_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Joins Courses and Terms to contain information related to a single occurrence of a course.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Course Offering</label><nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField><pluralLabel>Course Offerings</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/hed__Term__c.object
<CustomObject><fields>
        <fullName>hed__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Terms</relationshipLabel>
        <relationshipName>Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Term_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Unit of time in which academic activities are taking place.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Term</label><nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Terms</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/User.object
<CustomObject><fields>
        <fullName>User_Type__c</fullName>
        <label>User Type</label>
        <picklist>
            <picklistValues>
                <fullName>ASC</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><externalSharingModel>Read</externalSharingModel><sharingModel>Read</sharingModel></CustomObject>

classes/Test_Utility.cls
/*******************************************************************************************
Apex Class: Test_Utility
Description: Utility class for test data
**********************************************************************************************/


@isTest
public with sharing class Test_Utility {

     /*public static UserRole createRole(){
         UserRole r = new UserRole(name = 'TEST ROLE');
         return r;
     }*/
     
     public static User createTestUser(String userName, String profileName ){

        Id profileId;
        try{
            profileId = [SELECT Id FROM Profile WHERE  name =: profileName LIMIT 1 ].Id;
        }catch (Exception ex) {
            System.assert( false, profileName + ' profile does not exist in the system');
        }
        
        User testUser = new User();
        testUser.LastName = 'test ' + UserName;
        testUser.Alias = (userName.length() > 8 ) ?  userName.substring(0 , 8) : userName;
        testUser.Email = UserName+'@test.com';
        testUser.Username = UserName+UserName+'@test.com';
        testUser.ProfileId = profileId;
        testUser.CommunityNickname = 'a'+UserName;
        testUser.TimeZoneSidKey = 'America/New_York';
        testUser.LocaleSidKey = 'en_US';
        testUser.EmailEncodingKey = 'ISO-8859-1';
        testUser.LanguageLocaleKey = 'en_US';
        testUser.IsActive = true;
        
        if(profileName == 'Faculty' || profileName== 'LWC Consultant'){   //Community User     
            testUser.user_type__c = 'ASC';
            Account acc = createAccount(); 
            insert acc;
            List<contact> conList = createContact(1,UserInfo.getUserId(),false,acc.id);
            conList[0].accountId = acc.id;
            insert conList;     
            testUser.contactId = conList[0].id;
        } 
        else //Not a community user
        {
            UserRole r = new UserRole(name = 'TEST ROLE'); //Role is specified because Portal Account owner should have a role
            insert r;
            testUser.UserRoleId = r.Id; //Community Users dont have role
        }   
        return testUser;
    }
    
    public static Account createAccount(){
        Account acc = new Account();
        acc.name='Center for Academic Student Achievement'; // in USF_CoachAvailabilityUtils class getRecordType method acc recordtype is found depending on its name
        List<BusinessHours> bhs=[select id from BusinessHours where IsDefault=true];
        acc.BusinessHour__c = bhs[0].id;
        return acc;
    }
    
    public static App_Config__c createAppConfig(String Name, String TextValue){
        App_Config__c appConfig = new App_Config__c();
        appConfig.name = Name;
        appConfig.Text_Value__c = TextValue;
        return appConfig;
    }
    
    public static List<App_Config__c> createAppConfigList(){
        List<App_Config__c> appConfigList = new List<App_Config__c>();
        appConfigList.add(new App_Config__c(Name='Learning Center',Text_Value__c='Learning Center'));
        
        appConfigList.add(new App_Config__c(Name='Writing Center',Text_Value__c='Writing Center'));
        
        appConfigList.add(new App_Config__c(Name='Speaking Center',Text_Value__c='Speaking Center'));
        
        appConfigList.add(new App_Config__c(Name='CASA',Text_Value__c='Center for Academic Student Achievement'));
        appConfigList.add(new App_Config__c(Name='CASA Slot Type',Text_Value__c='CASA Slot'));
        appConfigList.add(new App_Config__c(Name='LWC Slot Type',Text_Value__c='LWC Slot'));
        appConfigList.add(new App_Config__c(Name='Scheduled Appointment',Text_Value__c='Scheduled'));
        appConfigList.add(new App_Config__c(Name='Dropin Appointment',Text_Value__c='Drop In'));
        appConfigList.add(new App_Config__c(Name='Confirm',Text_Value__c='Confirm'));
        appConfigList.add(new App_Config__c(Name='Pending',Text_Value__c='Pending'));
        appConfigList.add(new App_Config__c(Name='Cancel',Text_Value__c='Cancel'));
        appConfigList.add(new App_Config__c(Name='Missed',Text_Value__c='Missed'));
        appConfigList.add(new App_Config__c(Name='Check',Text_Value__c='Check'));
        appConfigList.add(new App_Config__c(Name='Complete',Text_Value__c='Complete'));
        appConfigList.add(new App_Config__c(Name='LWC Slot Complete Status',Text_Value__c='Complete'));
        appConfigList.add(new App_Config__c(Name='USF_CASAAppointmentMissedStatus',Text_Value__c='No Show'));
        appConfigList.add(new App_Config__c(Name='LWC Appointment Confirmed Status',Text_Value__c='Confirmed'));
        appConfigList.add(new App_Config__c(Name='Checkin',Text_Value__c='Checkin'));
        appConfigList.add(new App_Config__c(Name='CASA Appointment Complete Status',Text_Value__c='Complete'));
        appConfigList.add(new App_Config__c(Name='CASA Appointment Pending Status',Text_Value__c='Pending'));
        appConfigList.add(new App_Config__c(Name='CASA Appointment Confirmed Status',Text_Value__c='Confirmed'));
        appConfigList.add(new App_Config__c(Name='ASC User type',Text_Value__c='ASC'));
        appConfigList.add(new App_Config__c(Name='Student Checkin by Consultant',Text_Value__c='Checked-In'));
        appConfigList.add(new App_Config__c(Name='CASA Appointment Cancelled Status',Text_Value__c='Cancelled'));
        appConfigList.add(new App_Config__c(Name='Student Profile',Text_Value__c='Student'));
        appConfigList.add(new App_Config__c(Name='AvailabilityMeetingType_Phone',Text_Value__c='Phone'));
        
        return appConfigList;
    }
    
    public static hed__Term__c createTerm(Id accId){
        hed__Term__c term = new hed__Term__c();
        term.hed__Account__c = accId;      
        return term;
    }
    
    public static List<Contact> createContact(integer size, Id userId, Boolean isStudent, Id accId){
        List<Contact> conList = new List<Contact>();
        for(integer i=0;i<size;i++)
        {
            contact con = new contact();
            con.lastname='Test'+i;
            con.CWID__c = 'TestCWID'+i;
            con.AcademicSuccessCoach__c = userId;
            con.Student__c=isStudent;
            con.AccountId = accId;
            conList.add(con);
        }
        return conList;
    } 
    public static hed__Course_Offering__c createCourseOffering(id courseId, id termId){
        User usr = Test_Utility.createTestUser('testFaculty','Faculty');
        if(usr!=null)
            insert usr;
        hed__Course_Offering__c courseOffering = new hed__Course_Offering__c();
        courseOffering.hed__Course__c = courseId;
        courseOffering.hed__Section_ID__c = 'TestSection01';
        courseOffering.hed__Term__c = termId;
        //user loggedInUser=[Select id,contactid from User where id=:UserInfo.getUserId()];
        courseOffering.hed__Faculty__c = usr.contactid;
        return courseOffering;
        
    }
    public static hed__Course__c createCourse(Id accId){
        hed__Course__c course = new hed__Course__c();
        course.Name = 'TestCourse';
        course.hed__Account__c = accId;
        return course;
    }
    public static List<case> createCase(Integer size, Id contactId, String RecTypeName,Id courseOffId){
        List<case> caseList = new List<case>();
        Id idCaseRecordType= [Select Id From RecordType where RecordType.developername =: RecTypeName and SobjectType='Case' limit 1].id;      
        for(integer i=0;i<size;i++){
            Case cse = new case();
            cse.contactId = contactId;
            cse.Course_Offering__c = courseOffId;
            if(idCaseRecordType!=null)
                cse.RecordTypeId=idCaseRecordType;
            caseList.add(cse);
        }
        return caseList;
    }
    public static List<AppointmentContact__c> createAppointmentContact(Integer size, String RecTypeName, Id conId, Id slotId){
        List<AppointmentContact__c> appConList = new List<AppointmentContact__c>();
        Id appRecordTypeId= [Select Id From RecordType where RecordType.developername =:RecTypeName and SobjectType='AppointmentContact__c' limit 1].id;
        AppointmentContact__c appCon;
        for(integer i=0;i<size;i++)
        {
            appCon = new AppointmentContact__c();
            appCon.RecordTypeId = appRecordTypeId;
            appCon.Contact__c= conId;
            appCon.Canceled_Date_Time__c = System.now();
            appCon.Reason_for_Meeting__c = 'Academic Coaching';
            appCon.Status__c='Denied';  
            appCon.AppointmentSlot__c = slotId;
            appCon.Strike__c = false;
            appConList.add(appCon);
        } 
        return appConList;
    }
    
    public static Counselor_Availability_Definition__c createAvailability(Id accId, DateTime startTime){
        Counselor_Availability_Definition__c avail = new Counselor_Availability_Definition__c();
        User usr = createTestUser('testFaculty','LWC Consultant');
        insert usr;
        avail.Coach__c = usr.id;
        avail.Success_Center__c = accId;
        avail.Repeat__c = 'Only Once';
        avail.AppointmentType__c = 'Scheduled';
        
        avail.Start_Date_Time__c = StartTime;
        //DateTime testDateTime = 
        avail.End_Date_Time__c= avail.Start_Date_Time__c.addHours(3);
        return avail;
    }
    
    public static Counsellor_Availability__c createSlot(Id availabilityId){
        Counsellor_Availability__c slot = new Counsellor_Availability__c();
        slot.Start_Time__c = System.now().addHours(1);
        DateTime testDateTime = System.now();
        slot.End_Time__c = testDateTime.addHours(3);
        slot.Availability__c = availabilityId;
        return slot;
    }
    public static Event createEvent(Id relatedSlotId){ 
        Event evnt = new Event();
        evnt.WhatId = relatedSlotId;
        evnt.StartDateTime = System.now();
        DateTime testDateTime = System.now();
        evnt.EndDateTime = testDateTime.addHours(3);
        return evnt; 
    }
    
}