objects/Account.object
<CustomObject><fields>
        <fullName>Academic_Program_Type__c</fullName>
        <label>Academic Program Type</label>
        <picklist>
            <picklistValues>
                <fullName>Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minor</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Current_Term__c</fullName>
        <label>Current Term</label>
        <length>255</length>
        <type>Text</type>
    </fields><compactLayoutAssignment>hed__HEDA_Account_Compact_Layout</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>false</enableHistory><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>Private</sharingModel><recordTypes>
        <fullName>Administrative</fullName>
        <active>true</active>
        <description>An administrative account.</description>
        <label>Administrative</label>
    </recordTypes></CustomObject>

objects/Contact.object
<CustomObject><fields>
        <fullName>CWID__c</fullName>
        <description>The primary USF ID</description>
        <externalId>true</externalId>
        <label>CWID</label>
        <length>100</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Number_of_Units_in_Current_Term__c</fullName>
        <label>Number of Units in Current Term</label>
        <precision>3</precision>
        <scale>0</scale>
        
        <type>Number</type>
    </fields><fields>
        <fullName>Reason_Withdrawn__c</fullName>
        <label>Reason Withdrawn</label>
        <length>255</length>
        
        <type>Text</type>
    </fields><compactLayoutAssignment>hed__HEDA_Contact_Compact_Layout</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Eligible_Tutor_Courses__c.object
<CustomObject><fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Eligible_Tutor_Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>Course_Offering__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Course Offering</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This course is not being offered for tutoring this semester.</errorMessage>
            <filterItems>
                <field>hed__Course_Offering__c.LWC_Tutor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>hed__Course_Offering__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Search for a course from the current semester course offerings.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>hed__Course_Offering__c</referenceTo>
        <relationshipName>Eligible_Tutor_Courses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Eligible Tutor Course</label><nameField>
        <displayFormat>ETC-{00000}</displayFormat>
        <label>ETC ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Eligible Tutor Courses</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/hed__Course__c.object
<CustomObject><fields>
        <fullName>hed__Course_ID__c</fullName>
        <label>Course ID</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Course_Number__c</fullName>
        <label>Course Number</label>
        <length>3</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Subject_Name__c</fullName>
        <description>The full name of a subject related to a course.</description>
        <label>Subject Name</label>
        <length>175</length>
        <type>Text</type>
    </fields><fields>
        <fullName>hed__Account__c</fullName>
        <label>Department</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Course_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Academic course that a Department or School (the degree-granting Account type for the University) offers.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Course</label><nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Courses</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/hed__Course_Offering__c.object
<CustomObject><fields>
        <fullName>LWC_Tutor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LWC Tutor</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Current_Term__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Supports Current Course Offering Report functionality.</description>
        <label>Current Term</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>hed__Term__c</fullName>
        <label>Term</label>
        <referenceTo>hed__Term__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>hed__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>hed__End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>hed__Course__c</fullName>
        <label>Course</label>
        <referenceTo>hed__Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Course_Offering_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Joins Courses and Terms to contain information related to a single occurrence of a course.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Course Offering</label><nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField><pluralLabel>Course Offerings</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/hed__Term__c.object
<CustomObject><fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>hed__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>hed__End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>hed__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Terms</relationshipLabel>
        <relationshipName>Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Term_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Unit of time in which academic activities are taking place.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Term</label><nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Terms</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/USF_CourseAllocationControllerTest.cls
@isTest(seeAllData = false)
public class USF_CourseAllocationControllerTest {
    
    public static String termId = '';
    public static String courseId = '';
    public static User currentUser = new User();
    public static String studentId = '';
    public static String studentCWID = '';
    public static Eligible_Tutor_Courses__c etc1 = new Eligible_Tutor_Courses__c();
    
	public static testmethod void insertTestData(){
        //insert account
        Account eduInstitution = new Account();
        eduInstitution.Name = 'University of San Fransisco';
        eduInstitution.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Educational Institution').getRecordTypeId();
        eduInstitution.Current_Term__c = 'Fall 2016';
        insert eduInstitution;
        
        Account parentAcc = new Account();
        parentAcc.Name = 'Economics Department';
        parentAcc.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('University Department').getRecordTypeId();
        insert parentAcc;
        
        Account adminAcc = new Account();
        adminAcc.Name = 'Business Economics';
        adminAcc.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        insert adminAcc;
        
        //insert administrative account
        Account acc = new Account();
        acc.Name = 'Admin Account';
        acc.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Administrative').getRecordTypeId();
        acc.Parent = parentAcc;
        acc.Academic_Program_Type__c = 'Major';
        insert acc;
        
        //insert a term
        hed__Term__c term1 = new hed__Term__c();
        term1.Name = 'Fall 2016';
        term1.hed__Start_Date__c = System.today() - 1;
        term1.hed__End_Date__c = System.today() + 3;
        term1.hed__Account__c = eduInstitution.Id;
        insert term1;
        termId = term1.Id;
        
        //insert course
        hed__Course__c course1 = new hed__Course__c();
        course1.Name = 'Business of the World';
        course1.hed__Course_ID__c = 'BUS202';
        course1.hed__Account__c = acc.Id;
        course1.Course_Number__c = '201';
        course1.Subject_Name__c = 'Business';
        insert course1;
        courseId = course1.Id;
        
        //insert course offering
        hed__Course_Offering__c courseOffering1 = new hed__Course_Offering__c();
        courseOffering1.Name = 'BE202Fall2016';
        courseOffering1.hed__Term__c = term1.Id;
        courseOffering1.Current_Term__c = true;
        courseOffering1.hed__Course__c = course1.Id;
        courseOffering1.Active__c = true;
        courseOffering1.LWC_Tutor__c = true;
        insert courseOffering1;
        
        hed__Course_Offering__c courseOffering2 = new hed__Course_Offering__c();
        courseOffering2.Name = 'BE202Fall2016';
        courseOffering2.hed__Term__c = term1.Id;
        courseOffering2.Current_Term__c = true;
        courseOffering2.hed__Course__c = course1.Id;
        courseOffering2.Active__c = true;
        courseOffering2.LWC_Tutor__c = true;
        insert courseOffering2;
        
        hed__Course_Offering__c courseOffering4 = new hed__Course_Offering__c();
        courseOffering4.Name = 'BE202Fall2016';
        courseOffering4.hed__Term__c = term1.Id;
        courseOffering4.Current_Term__c = true;
        courseOffering4.hed__Course__c = course1.Id;
        courseOffering4.Active__c = true;
        courseOffering4.LWC_Tutor__c = true;
        insert courseOffering4;
        
        hed__Course_Offering__c courseOffering3 = new hed__Course_Offering__c();
        courseOffering3.Name = 'CE202Fall2016';
        courseOffering3.hed__Term__c = term1.Id;
        courseOffering3.Current_Term__c = true;
        courseOffering3.hed__Course__c = course1.Id;
        courseOffering3.Active__c = true;
        courseOffering3.LWC_Tutor__c = true;
        insert courseOffering3;
        
        currentUser = [select id from User where id=: UserInfo.getUserId() limit 1];
        //create student contact
        List<Contact> contacts = Test_Utility.createContact(1, currentUser.Id, true, adminAcc.Id);
        Contact student = contacts[0];
        System.debug('**student: '+student);
        insert student;
        studentId = student.Id;
        studentCWID = student.CWID__c;
        System.debug('**studentId: '+student.Id);
        
        //create eligible tutor courses
        etc1 = new Eligible_Tutor_Courses__c();
        etc1.Course_Offering__c = courseOffering2.Id;
        etc1.Contact__c = student.Id;
        insert etc1;
        
        etc1 = new Eligible_Tutor_Courses__c();
        etc1.Course_Offering__c = courseOffering1.Id;
        etc1.Contact__c = student.Id;
        insert etc1;
                        
    }
    
    static testmethod void validateGetfacultyInfoByCWID(){
        Test.startTest();
        //Negative scenario
        ApexPages.StandardController stdcon = new ApexPages.StandardController(etc1);
        USF_CourseAllocationController controller = new USF_CourseAllocationController(stdcon);
        System.debug('Student');
        controller.CWID = studentCWID;
        controller.selectedStudentId = studentId;
        controller.getfacultyInfoByCWID();
        //Positive Scenario
        insertTestData();
        stdcon = new ApexPages.StandardController(etc1);
        controller = new USF_CourseAllocationController(stdcon);
        System.debug('Student');
        controller.CWID = studentCWID;
        controller.selectedStudentId = studentId;
        controller.getfacultyInfoByCWID();
        Integer i = 0;
        for(List<USF_CourseAllocationController.courseWrapper> cw : controller.courseMap.Values()){
            for(USF_CourseAllocationController.courseWrapper wrapObj : cw){
                if(Math.mod(i,2)==0){
                    wrapObj.selected = true;
                    i++;
                }
            }
        }
        controller.addCourses();
        i=0;
        for(List<USF_CourseAllocationController.courseWrapper> cw : controller.addedCourseMap.Values()){
            for(USF_CourseAllocationController.courseWrapper wrapObj : cw){
                if(Math.mod(i,2)==0){
                    wrapObj.selected = true;
                    i++;
                }
            }
        }
        controller.removeCourses();
        controller.saveCourses();
        Test.stopTest();
    }
    
    

}