objects/App_Config__c.object
<CustomObject><fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <type>TextArea</type>
    </fields><customSettingsType>List</customSettingsType><description>Stores all configurable settings for USF</description><enableFeeds>false</enableFeeds><label>App Config</label><visibility>Public</visibility></CustomObject>

objects/AppointmentContact__c.object
<CustomObject><fields>
        <fullName>AppointmentSlot__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Appointment Slot</label>
        <referenceTo>Counsellor_Availability__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointment_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointment_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Preferred_Phone__c</fullName>
        <inlineHelpText>Phone received from the student when booking an appointment</inlineHelpText>
        <label>Preferred Phone</label>
        <type>Phone</type>
    </fields><fields>
        <fullName>Reason_for_Meeting__c</fullName>
        <label>Appointment Reasons</label>
        <picklist>
            <picklistValues>
                <fullName>Academic Coaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Probation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Concerns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housing / Residence Hall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leave of Absence / Withdrawal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Concerns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major / Minor Exploration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Study Abroad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Student Survey</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields>
        <fullName>Referred_By__c</fullName>
        <label>Referred By</label>
        <picklist>
            <picklistValues>
                <fullName>Faculty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent / Guardian</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields>
        <fullName>Referrer_Name__c</fullName>
        <label>Referrer Name</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Start_Time__c</fullName>
        <formula>IF(
  OR(
    VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) = 0,
    VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) = 12
  ),
  "12",
  TEXT( VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) 
   -
   IF( 
     VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) &lt; 12, 
     0, 
     12 
   ) 
  )
)
&amp; ":" &amp;
MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 15, 2 )
&amp; " " &amp;
IF(
  VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) &lt; 12,
  "AM",
  "PM"
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Time</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>175</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Appointments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Notes</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Appointment</label><nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Appointments</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Contact.object
<CustomObject><fields>
        <fullName>AcademicSuccessCoach__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Academic Success Coach</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notEqual</operation>
                <value>Customer Community User</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Number_of_Units_in_Current_Term__c</fullName>
        <label>Number of Units in Current Term</label>
        <precision>3</precision>
        <scale>0</scale>
        
        <type>Number</type>
    </fields><fields>
        <fullName>Reason_Withdrawn__c</fullName>
        <label>Reason Withdrawn</label>
        <length>255</length>
        
        <type>Text</type>
    </fields><compactLayoutAssignment>hed__HEDA_Contact_Compact_Layout</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Counsellor_Availability__c.object
<CustomObject><fields>
        <fullName>Availability__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used to store the reference to Availability</description>
        <label>Availability</label>
        <referenceTo>Counselor_Availability_Definition__c</referenceTo>
        <relationshipLabel>Slots (Availability)</relationshipLabel>
        <relationshipName>Slots</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>175</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed by Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Appointments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Slot</label><nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Coach Availability Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Slots</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Counselor_Availability_Definition__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Availability</label><nameField>
        <displayFormat>CAD-{0000}</displayFormat>
        <label>Coach Availability Definition Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Availability</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Read</sharingModel></CustomObject>

classes/USF_FDAppointmentDetailsController.cls
/************************************************************************************
// Name             : USF_FDAppointmentDetailsController 
// Description      : Controller for USF_FDAppointmentDetails Visualforce page
// Created By       : Manjunath Singh
// Created Date     : 09/24/2016
// ************************Version Updates********************************************
// Date             Developer           Description
// -----------------------------------------------------------------------------------
// 09/24/2016       Manjunath Singh       Created
// ************************************************************************************/
public class USF_FDAppointmentDetailsController {

    public String appointmentDate {get;set;}
    public String appointmentTime {get;set;} 
    public List<AppointmentContact__c> appointmentRecord{get;set;}
    public string appId {get;set;}


    public USF_FDAppointmentDetailsController(ApexPages.StandardController controller) {
    
    appointmentRecord=new List<AppointmentContact__c>();
    
    appId=Apexpages.currentPage().getParameters().get('appId');
    
    populateAppDetails();
    
    }
    
  /**********************************************************************
   Description: This method is used to populate appointments information
   Return type: Void
   Parameters: None
   Created By: Manjunath Singh
  ***********************************************************************/
    
    public void populateAppDetails(){
    
        try{
            
            appointmentRecord=[Select id,AppointmentSlot__r.Start_Time__c,Preferred_Phone__c,AppointmentSlot__r.Availability__r.Coach__r.name,Reason_for_Meeting__c,Location__c,
            Status__c,Contact__r.AcademicSuccessCoach__r.Name,Referred_By__c,Referrer_Name__c,Name from AppointmentContact__c where id=:appId];
            
            if(appointmentRecord.size()!=0){
                   
                  if(appointmentRecord[0].AppointmentSlot__r.Start_Time__c!= null){
                        appointmentDate = appointmentRecord[0].AppointmentSlot__r.Start_Time__c.format('M/d/yyyy');
                        appointmentTime = appointmentRecord[0].AppointmentSlot__r.Start_Time__c.format('hh:mm a');
        }
            }
        
        }
        catch(Exception e){
        
        
        }
    
    
    
    }
    
  /**********************************************************************
   Description: This method is used for cancel appointment functionality
   Return type: Void
   Parameters: None
   Created By: Manjunath Singh
  ***********************************************************************/
    
    public void cancelAppointment(){
    
    if(appointmentRecord[0].status__c!=App_Config__c.getInstance('CASA Appointment Cancelled Status').Text_Value__c){
    
    appointmentRecord[0].status__c=App_Config__c.getInstance('CASA Appointment Cancelled Status').Text_Value__c;
    
    try{
    
        update appointmentRecord[0];
    
    }
    catch(Exception e){
    
    }
   }
    
 }
    

}