objects/App_Config__c.object
<CustomObject><fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <type>TextArea</type>
    </fields><customSettingsType>List</customSettingsType><description>Stores all configurable settings for USF</description><enableFeeds>false</enableFeeds><label>App Config</label><visibility>Public</visibility></CustomObject>

objects/AppointmentContact__c.object
<CustomObject><fields>
        <fullName>AppointmentSlot__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Appointment Slot</label>
        <referenceTo>Counsellor_Availability__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointment_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><fields>
        <fullName>CWID__c</fullName>
        <formula>Contact__r.CWID__c</formula>
        <label>CWID</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointment_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Reason_for_Meeting__c</fullName>
        <label>Appointment Reasons</label>
        <picklist>
            <picklistValues>
                <fullName>Academic Coaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Probation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Concerns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housing / Residence Hall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leave of Absence / Withdrawal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Concerns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major / Minor Exploration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Study Abroad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Student Survey</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields>
        <fullName>Referred_By__c</fullName>
        <label>Referred By</label>
        <picklist>
            <picklistValues>
                <fullName>Faculty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent / Guardian</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields>
        <fullName>Start_Time__c</fullName>
        <formula>IF(
  OR(
    VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) = 0,
    VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) = 12
  ),
  "12",
  TEXT( VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) 
   -
   IF( 
     VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) &lt; 12, 
     0, 
     12 
   ) 
  )
)
&amp; ":" &amp;
MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 15, 2 )
&amp; " " &amp;
IF(
  VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) &lt; 12,
  "AM",
  "PM"
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Time</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>175</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Appointments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Notes</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Appointment</label><nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Appointments</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Contact.object
<CustomObject><fields>
        <fullName>AcademicSuccessCoach__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Academic Success Coach</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notEqual</operation>
                <value>Customer Community User</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>CWID__c</fullName>
        <description>The primary USF ID</description>
        <externalId>true</externalId>
        <label>CWID</label>
        <length>100</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Number_of_Units_in_Current_Term__c</fullName>
        <label>Number of Units in Current Term</label>
        <precision>3</precision>
        <scale>0</scale>
        
        <type>Number</type>
    </fields><fields>
        <fullName>Preferred_Name__c</fullName>
        <label>Preferred Name</label>
        <length>175</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Reason_Withdrawn__c</fullName>
        <label>Reason Withdrawn</label>
        <length>255</length>
        
        <type>Text</type>
    </fields><compactLayoutAssignment>hed__HEDA_Contact_Compact_Layout</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Counsellor_Availability__c.object
<CustomObject><fields>
        <fullName>Availability__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used to store the reference to Availability</description>
        <label>Availability</label>
        <referenceTo>Counselor_Availability_Definition__c</referenceTo>
        <relationshipLabel>Slots (Availability)</relationshipLabel>
        <relationshipName>Slots</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Selected_Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Selected Course</label>
        <referenceTo>hed__Course_Offering__c</referenceTo>
        <relationshipLabel>Slots</relationshipLabel>
        <relationshipName>Slots</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>175</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed by Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Appointments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Slot</label><nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Coach Availability Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Slots</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Counselor_Availability_Definition__c.object
<CustomObject><fields>
        <fullName>Coach__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coach</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Availability_Definition</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>LWC, Cowell 215</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cowell 212</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC, Malloy 103</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>McLaren 107</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gleeson Library</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Front Desk Online/Canvas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UC 3rd Floor Lounge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UC 4th Floor Lounge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UC 5th Floor Lounge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hayes-Healy Formal Lounge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gillson Lounge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fromm Lounge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outtakes Cafe (LoMo by OneCard Office)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crossroads Cafe outside Bookstore Entrance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harney 512</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cowell 417/418</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kalmanovitz 309 Library</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>University Center, 3rd floor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pleasanton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>San Jose</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sacramento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downtown SF</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Availability</label><nameField>
        <displayFormat>CAD-{0000}</displayFormat>
        <label>Coach Availability Definition Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Availability</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Read</sharingModel></CustomObject>

objects/hed__Course_Offering__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Course_Offering_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Joins Courses and Terms to contain information related to a single occurrence of a course.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Course Offering</label><nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField><pluralLabel>Course Offerings</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/USF_SchedulingAppointmentController.cls
/************************************************************************************
// Name             : USF_SchedulingAppointmentController 
// Description      : Controller for USF_SchedulingAppointment Visualforce page
// Created By       : Manjunath Singh
// Created Date     : 09/14/2016
// ************************Version Updates********************************************
// Date             Developer           Description
// -----------------------------------------------------------------------------------
// 09/14/2016       Manjunath Singh       Created
// ************************************************************************************/

public with sharing class USF_SchedulingAppointmentController {

    public String slotId;
    public String slotDate {get;set;}
    public String slotTime {get;set;} 
    public List<Counsellor_Availability__c> slots =new List<Counsellor_Availability__c>();
    public Counsellor_Availability__c selectedSlot {get;set;}
    public String selectedStudent {get;set;}
    public String selectedReferredBy {get;set;}
    public boolean showStudentDetails {get;set;}
    public List<Contact> selStudentDetails{get;set;}
    public AppointmentContact__c newAppointment {get;set;}
    public String message {get;set;}  
    public String selectedStudentId {get;set;} 
    public boolean isException {get;set;}
    
    //Constructor
    public USF_SchedulingAppointmentController(ApexPages.StandardController controller) {
        showStudentDetails =false;
        isException=false;
        selectedStudent='';
        message='';
        selectedReferredBy='None';
        selStudentDetails=new List<contact>();
        slots=new List<Counsellor_Availability__c>();
        slotId=Apexpages.currentPage().getParameters().get('sid');
        populateSlotInformation();  
        
        //Creating an appointment
        newAppointment =(AppointmentContact__c)controller.getRecord();
        Id devRecordTypeId = Schema.SObjectType.AppointmentContact__c.getRecordTypeInfosByName().get('CASA Appointment').getRecordTypeId();
        newAppointment.recordTypeid=devRecordTypeId;
        
        
    }
  
  
  public void populateSlotInformation(){
  
  try{
  
      slots=[SELECT Id, Name, Start_Time__c,End_Time__c,Availability__r.Coach__r.name,Location__c, Selected_Course__r.Name FROM Counsellor_Availability__c where id=:slotId];
     
      if(slots.size()!=0){
          selectedSlot=slots[0];
          if(selectedSlot.Start_Time__c != null){
                slotDate = selectedSlot.Start_Time__c.format('M/d/yyyy');
                slotTime = selectedSlot.Start_Time__c.format('h:mm a')+' - '+selectedSlot.End_Time__c.format('h:mm a');
            }  
      }
  
     }
  catch(Exception e){
  
   }
  
  
} 

    public void lookUpButtonAction(){

    if(selectedStudent!=null && selectedStudent!='' && selectedStudent.contains('(')){
        String whereClause='';
        if(selectedStudentId!=null && selectedStudentId!=''){
          whereClause=' WHERE Id=\''+String.escapeSingleQuotes(selectedStudentId)+'\'';
        }
        else{
          String cwid=selectedStudent.subString(selectedStudent.indexOf('(')+1, selectedStudent.lastIndexOf(')'));
          whereClause=' WHERE cwid__c=\''+String.escapeSingleQuotes(cwid)+'\'';
          
        }
        
        try{
        
        selStudentDetails=[Select id,name,PhotoUrl,Major__c,Preferred_Name__c,AcademicSuccessCoach__r.name,Phone,CWID__c,Email from contact whereClause LIMIT 1];
        selStudentDetails=Database.query('Select id,name,PhotoUrl,Major__c,Preferred_Name__c,AcademicSuccessCoach__r.name,Phone,CWID__c,Email from contact '+whereClause+' LIMIT 1');
            if(selStudentDetails.size()!=0){     
                showStudentDetails=true;              
            }
        
        }
        catch(Exception e){
        
        }

}

}

// Reason for Meeting multiselect picklist to checkbox conversion
    public String[] reasons = new String[]{};
    
    public String[] getreasons() {
        return reasons;
    }

    public void setreasons(String[] reasons) {
        this.reasons = reasons;
    }
    
    public List<SelectOption> getReasonforPicklist()
    {
      List<SelectOption> options = new List<SelectOption>();
            
       Schema.DescribeFieldResult fieldResult =
     AppointmentContact__c.Reason_for_Meeting__c.getDescribe();
       List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            
       for( Schema.PicklistEntry f : ple)
       {
          options.add(new SelectOption(f.getLabel(), f.getValue()));
       }       
       return options;
    }
    
    public List<SelectOption> getReferedByPicklist()
    {
      List<SelectOption> options = new List<SelectOption>();
            
       Schema.DescribeFieldResult fieldResult =
     AppointmentContact__c.Referred_By__c.getDescribe();
       List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
       options.add(new SelectOption('None', 'None'));
       for( Schema.PicklistEntry f : ple)
       {
          options.add(new SelectOption(f.getLabel(), f.getValue()));
       }       
       return options;
    }
    
    public PageReference cancelAppointment() {
        return Page.USF_FrontDeskStaffDashboard;
    }
    
    public pageReference createAppointment(){
    
    //Added to check the coach leave period
    String leaveValidation = USF_CenterRulesUtil.validateCASACoachLeave('CASA',slotId);//added one more parameter so all messages get returned from centerRulesUtil class to maintain one source -- Nishit
    if(String.isBlank(leaveValidation)){
    
    //if(selectedReferredBy!=null){
        if(selectedReferredBy != 'None'){
            newAppointment.Referred_By__c=selectedReferredBy;
        }
        newAppointment.Contact__c=selStudentDetails[0].id;
        newAppointment.AppointmentSlot__c=slotId;
        newAppointment.status__c=App_Config__c.getInstance('CASA Appointment Confirmed Status').Text_Value__c;
    
    //}
    
        if(reasons!=null){
            for(String reason: reasons){
                        if(newAppointment.Reason_for_Meeting__c == null || newAppointment.Reason_for_Meeting__c== '')
                            newAppointment.Reason_for_Meeting__c= reason+ ';';

                         else
                            newAppointment.Reason_for_Meeting__c = newAppointment.Reason_for_Meeting__c+ reason + ';';
                    } 
         }
         
         try{
         
             insert newAppointment;
             message=App_Config__c.getInstance('Casa Appointment Submitted message').Text_Value__c;
         
         }
         catch(Exception e){
             isException=true;
             message='Error in submitting request'+e.getmessage();
         
         }
    return null;
    
    }else{
    
    //To-do: Change message string as required.
    message = leaveValidation;
    
    return null;
    }
    
    }
 

}