objects/App_Config__c.object
<CustomObject><customSettingsType>List</customSettingsType><description>Stores all configurable settings for USF</description><enableFeeds>false</enableFeeds><label>App Config</label><visibility>Public</visibility></CustomObject>

objects/Case.object
<CustomObject><fields>
        <fullName>Areas_for_improvement__c</fullName>
        <description>This field holds the areas for improvement values in Reasons Section on EAP Report Form page.</description>
        <label>Areas for Improvement</label>
        <picklist>
            <picklistValues>
                <fullName>Attendance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Participation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Grades</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields>
        <fullName>Description</fullName>
        
    </fields><fields>
        <fullName>Origin</fullName>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit - Drop in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit - Scheduled Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WebTrack</fullName>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields>
        <fullName>OwnerId</fullName>
        
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Priority</fullName>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Reason</fullName>
        <picklist>
            <picklistValues>
                <fullName>Academic Coaching</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Disqualification</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Form Processing</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Integrity</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Probation</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Appointment Information</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>CMBIT</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Dean's Letter / Tuition Adjustment</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Disability Related Issues</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Disruptive Behavior</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Early Alert</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty/Student Complaint</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty Notification</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Needs</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Grade Appeal / Grade Change</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Graduation</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Homesickness</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Housing / Residence Hall</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Leave of Absence/Withdrawal from USF</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Loss / Grief</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Major / Minor Exploration</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Health</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>New Student Survey</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Referral</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Assistance</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>SOM Waitlist</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Study Abroad</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Substance Abuse</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Underenrolled</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Status</fullName>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
                <closed>false</closed>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <closed>false</closed>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
                <closed>true</closed>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
                <closed>true</closed>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Subject</fullName>
        
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Type</fullName>
        <picklist>
            <picklistValues>
                <fullName>Problem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feature Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Question</fullName>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields>
        <fullName>Work__c</fullName>
        <description>This field holds the 'Work' values of Reasons Section on EAP Report Form page.</description>
        <label>Work</label>
        <picklist>
            <picklistValues>
                <fullName>Quality of work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Late Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lack of Study Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time Management Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lack of Motivation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performing below a "C"</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>Private</sharingModel><recordTypes>
        <fullName>EAP_Report</fullName>
        <active>true</active>
        <businessProcess>EAP</businessProcess>
        <label>EAP Report</label>
    </recordTypes></CustomObject>

objects/hed__Course__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Course_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Academic course that a Department or School (the degree-granting Account type for the University) offers.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Course</label><nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Courses</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/hed__Course_Offering__c.object
<CustomObject><fields>
        <fullName>hed__Term__c</fullName>
        <label>Term</label>
        <referenceTo>hed__Term__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>hed__Course__c</fullName>
        <label>Course</label>
        <referenceTo>hed__Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Course_Offering_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Joins Courses and Terms to contain information related to a single occurrence of a course.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Course Offering</label><nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField><pluralLabel>Course Offerings</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/hed__Term__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Term_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Unit of time in which academic activities are taking place.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Term</label><nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Terms</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/USF_FacultyStaffEAPFormControllerTest.cls
/** Class Name   : USF_FacultyStaffEAPFormControllerTest
 *  Description  : Test Class for USF_FacultyStaffEAPFormController
 *  Created By   : Ankit Jain
 *  Created On   : 3-Oct-2016
 *  Modification Log:
   ------------------------------------------------------------------------------------
   Developer                       Date                Description
   ------------------------------------------------------------------------------------
   Ankit Jain                     3-Oct-2016          Original Version
 */
@isTest
public with sharing class USF_FacultyStaffEAPFormControllerTest{
    @isTest
    static void TestUSF_FacultyStaffEAPFormController(){
        User usr = Test_Utility.createTestUser('testusername','System Administrator');
        if(usr!=null)
            insert usr;
        List<Contact> conList; 
        hed__Course_Offering__c courseOffering;
        List<Case> caseList;   
        System.runAs(usr){
        
           
            Account acc = Test_Utility.createAccount();
            if(acc!=null)
                insert acc; 
            List<App_Config__c> appConfigList = new List<App_Config__c>();  
            App_Config__c appConfig = Test_Utility.createAppConfig('EAP Report RecordType','EAP Report');
            if(appConfig!=null)
                appConfigList.add(appConfig);   
            App_Config__c appConfig2 = Test_Utility.createAppConfig('EAP Form Referral value','Referral');
            if(appConfig2!=null)
                appConfigList.add(appConfig2); 
            App_Config__c appConfig3 = Test_Utility.createAppConfig('EAP Form Submit Success Message','Referral has been submitted successfully.');
            if(appConfig3!=null)
                appConfigList.add(appConfig3);   
            if(appConfigList!= null && appConfigList.size()>0)
                insert appConfigList ;
            
            conList = Test_Utility.createContact(1,usr.id,true,acc.id);
            if(conList!=null && conList.size()>0)
                insert conList;     
            hed__Course__c course = Test_Utility.createCourse(acc.id);
            if(course!=null)
                insert course;
            hed__Term__c term = Test_Utility.createTerm(acc.id);
            if(term!=null)
                insert term; 
           
            courseOffering = Test_Utility.createCourseOffering(course.id,term.id);          
            if(courseOffering != null)
                insert courseOffering;
            caseList = Test_Utility.createCase(2,conList[0].id,'EAP_Report',courseOffering.id);
            if(caseList!=null && caseList.size()>0)
                insert caseList[1];
                caseList[1].Areas_for_improvement__c = 'Attendance';
            caseList[1].work__c = 'Quality of work';
            update CaseList[1];
        }         
        List<User> usrList = [select id from user where profile.Name='Faculty' ];         
        System.runAs(usrList[0]){        
            Test.startTest();
            Pagereference pg = Page.USF_FacultyStaffEAPForm;
            Test.setCurrentPage(pg);
            ApexPages.currentPage().getParameters().put('cId',courseOffering.id);
            ApexPages.currentPage().getParameters().put('view','true');
            ApexPages.currentPage().getParameters().put('eapId',caseList[0].id);
            ApexPages.currentPage().getParameters().put('sId',conList[0].id);
            ApexPages.currentPage().getParameters().put('ascId',usr.id);
            USF_FacultyStaffEAPFormController fc = new USF_FacultyStaffEAPFormController(new ApexPages.Standardcontroller(caseList[0]));
            List<String> selectedWork = fc.getselectedWork();
            fc.setselectedWork(selectedWork);
            List<String> selRecom = fc.getselectedRecomendations();
            fc.setselectedRecomendations(selRecom); 
            fc.areasOfImp.add('Attendance');
            fc.areasOfImp.add('Participation');
            fc.selectedWork.add('Quality of work');
            fc.selectedWork.add('Late work');
            fc.selectedRecomendations.add('See Instructor');
            fc.selectedRecomendations.add('Tutoring');
            Pagereference pg2 = fc.submitReferral();
            List<String> area = fc.getareasOfImp();
            fc.setareasOfImp(area);
            List<selectOption> aoi = fc.getAreasOfImprovement();
            List<selectOption> wv = fc.getWorkValues();
            List<selectOption> rv = fc.getRecommendationValues();
            System.assertEquals(9,rv.size());
            fc.populateViewForm();
            
            ApexPages.currentPage().getParameters().put('eapId',caseList[1].id);
            USF_FacultyStaffEAPFormController fc2 = new USF_FacultyStaffEAPFormController(new ApexPages.Standardcontroller(caseList[1]));
            fc2.populateViewForm();
            Test.stopTest();
        }              
    }
    
}