objects/App_Config__c.object
<CustomObject><fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <type>TextArea</type>
    </fields><customSettingsType>List</customSettingsType><description>Stores all configurable settings for USF</description><enableFeeds>false</enableFeeds><label>App Config</label><visibility>Public</visibility></CustomObject>

objects/AppointmentContact__c.object
<CustomObject><fields>
        <fullName>CWID__c</fullName>
        <formula>Contact__r.CWID__c</formula>
        <label>CWID</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Date_Time__c</fullName>
        <formula>AppointmentSlot__r.Start_Time__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date/Time</label>
        <type>DateTime</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Appointment</label><nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Appointments</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Case.object
<CustomObject><fields>
        <fullName>CWID__c</fullName>
        <formula>Contact.CWID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CWID</label>
        <type>Text</type>
    </fields><fields>
        <fullName>ContactFirstName__c</fullName>
        <formula>Contact.FirstName</formula>
        <label>ContactFirstName</label>
        <type>Text</type>
    </fields><fields>
        <fullName>ContactLastName__c</fullName>
        <formula>Contact.LastName</formula>
        <label>ContactLastName</label>
        <type>Text</type>
    </fields><fields>
        <fullName>CourseName__c</fullName>
        <formula>Course_Offering__r.hed__Course__r.Name</formula>
        <label>Course Name</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Course_Section__c</fullName>
        <formula>Course_Offering__r.hed__Section_ID__c</formula>
        <label>Course Section</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Description</fullName>
        
    </fields><fields>
        <fullName>Origin</fullName>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit - Drop in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit - Scheduled Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WebTrack</fullName>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields>
        <fullName>OwnerId</fullName>
        
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Priority</fullName>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Reason</fullName>
        <picklist>
            <picklistValues>
                <fullName>Academic Coaching</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Disqualification</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Form Processing</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Integrity</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Probation</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Appointment Information</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>CMBIT</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Dean's Letter / Tuition Adjustment</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Disability Related Issues</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Disruptive Behavior</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Early Alert</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty/Student Complaint</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty Notification</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Needs</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Grade Appeal / Grade Change</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Graduation</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Homesickness</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Housing / Residence Hall</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Leave of Absence/Withdrawal from USF</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Loss / Grief</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Major / Minor Exploration</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Health</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>New Student Survey</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Referral</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Assistance</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>SOM Waitlist</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Study Abroad</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Substance Abuse</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Underenrolled</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Status</fullName>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
                <closed>false</closed>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <closed>false</closed>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
                <closed>true</closed>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
                <closed>true</closed>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Subject</fullName>
        
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Type</fullName>
        <picklist>
            <picklistValues>
                <fullName>Problem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feature Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Question</fullName>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Contact.object
<CustomObject><fields>
        <fullName>CWID__c</fullName>
        <description>The primary USF ID</description>
        <externalId>true</externalId>
        <label>CWID</label>
        <length>100</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Number_of_Units_in_Current_Term__c</fullName>
        <label>Number of Units in Current Term</label>
        <precision>3</precision>
        <scale>0</scale>
        
        <type>Number</type>
    </fields><fields>
        <fullName>Reason_Withdrawn__c</fullName>
        <label>Reason Withdrawn</label>
        <length>255</length>
        
        <type>Text</type>
    </fields><compactLayoutAssignment>hed__HEDA_Contact_Compact_Layout</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/USF_FacultyDashBoardController.cls
/************************************************************************************
// Name             : USF_FacultyDashBoardController 
// Description      : Controller for USF_FacultyDashBoard Visualforce page
// Created By       : Manjunath Singh
// Created Date     : 09/14/2016
// ************************Version Updates********************************************
// Date             Developer           Description
// -----------------------------------------------------------------------------------
// 09/14/2016       Manjunath Singh       Created
// ************************************************************************************/
public with sharing class USF_FacultyDashBoardController {

    //Variable to store eapReport records
    public ApexPages.StandardSetController eapReportRecords;  
    public Map<Id,String> eapDateMap {get; set;}
    public Integer eapPageSize{get;set;}
    public Integer noOfRecords{get; set;}

    //Constructor
    public USF_FacultyDashBoardController (){
    
    eapDateMap=new Map<Id,String>();
    Id eapRecordTypeId = Schema.SObjectType.case.getRecordTypeInfosByName().get(App_Config__c.getInstance('EAP Report RecordType').Text_Value__c).getRecordTypeId();
    
    eapPageSize=5;
    eapReportRecords= new ApexPages.StandardSetController(Database.getQueryLocator(
                [SELECT id,contact.name,CWID__c,ContactFirstName__c,ContactLastName__c,contact.CWID__c,CourseName__c, Course_Section__c ,createddate 
                FROM case 
                WHERE createdById=:UserInfo.getUserId() 
                AND recordTypeID=:eapRecordTypeId
                ORDER BY createddate desc,ContactLastName__c asc
                LIMIT 10000])
                );
    //eapReportRecords=USF_DBUtil.getFacultyDashboardReports(eapRecordTypeId);
    
    eapReportRecords.setPageSize(eapPageSize);
    noOfRecords=eapReportRecords.getResultSize();
    }
    
    //This method is used to format createddatetime
    
   /* public void formatCreatedDateTime(){
    
     for(AppointmentContact__c app: appointments){   
            if(app.Date_Time__c != null && UserInfo.getTimeZone().getID()!=null){
            appointmentDateMap.put(app.Id,app.Date_Time__c.format('d MMM yy, HH:mm a', UserInfo.getTimeZone().getID()));
            }
    
    }*/
    
    
    /**************************************************************
    Description: This method is used to populate eap report table
    Return type: List<case>
    Parameters: None
    Created By: Manjunath Singh
    ***************************************************************/
    public List<case> getEAPReports() {
    
    for(Case caseRecord: (List<case>)eapReportRecords.getRecords()){ 
    system.debug('Record:'+caseRecord.contact.name);  
          //  if(app.Date_Time__c != null && UserInfo.getTimeZone().getID()!=null){
            eapDateMap.put(caseRecord.Id,caseRecord.createddate.format('EEEE,MMM d yyyy,hh:mm a'));
            //caseRecord.createddate.format('EEEE,MMM d yyyy,hh:mm a');
           // }
    }
        return (List<case>) eapReportRecords.getRecords();
    }
    
    //Pagination methods for EapReport Records
    public Boolean hasNext {
        get {
            return eapReportRecords.getHasNext();
        }
        set;
    }
    public Boolean hasPrevious {
        get {
            return eapReportRecords.getHasPrevious();
        }
        set;
    }
  
    public Integer pageNumber {
        get {
            return eapReportRecords.getPageNumber();
        }
        set;
    }
  
    public void first() {
        eapReportRecords.first();
    }
  
    public void last() {
        eapReportRecords.last();
    }
  
    public void previous() {
        eapReportRecords.previous();
    }
  
    public void next() {
        eapReportRecords.next();    
    }
    
    
}