objects/App_Config__c.object
<CustomObject><fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <type>TextArea</type>
    </fields><customSettingsType>List</customSettingsType><description>Stores all configurable settings for USF</description><enableFeeds>false</enableFeeds><label>App Config</label><visibility>Public</visibility></CustomObject>

objects/AppointmentContact__c.object
<CustomObject><fields>
        <fullName>Center__c</fullName>
        <inlineHelpText>This field will get updated by the workflow on creation of the appointment</inlineHelpText>
        <label>Center</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is in addition to Slot lookup so that Consultant  can be given access to the Appointment to take actions. This need to be autopopulated using automation</description>
        <label>Consultant</label>
        <referenceTo>Consultant__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Notes__c</fullName>
        <description>Notes provided by the student during appointment scheduling (LWC)</description>
        <label>Background Notes (Visible to Students)</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Start_Time__c</fullName>
        <formula>IF(
  OR(
    VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) = 0,
    VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) = 12
  ),
  "12",
  TEXT( VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) 
   -
   IF( 
     VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) &lt; 12, 
     0, 
     12 
   ) 
  )
)
&amp; ":" &amp;
MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 15, 2 )
&amp; " " &amp;
IF(
  VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) &lt; 12,
  "AM",
  "PM"
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Time</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>175</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Appointments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Notes</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>In Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone/Online</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Appointment</label><nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Appointments</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Consultant__c.object
<CustomObject><fields>
        <fullName>Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Center</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.LWC_Account_Flag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Consultants</relationshipLabel>
        <relationshipName>Consultants</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Consultant</label><nameField>
        <label>Consultant Record Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Consultants</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

objects/Counsellor_Availability__c.object
<CustomObject><fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Center__c</fullName>
        <formula>Availability__r.Success_Center__r.Name</formula>
        <label>Center</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Coach_Full_Name__c</fullName>
        <description>FirstName LastName</description>
        <formula>Coach_First_Name__c &amp; " " &amp;  Coach_Last_Name__c</formula>
        <label>Coach Full Name</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant</label>
        <referenceTo>Consultant__c</referenceTo>
        <relationshipLabel>Slots</relationshipLabel>
        <relationshipName>Slots</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Noofstudentsregistered__c</fullName>
        <description>No of students registered</description>
        <label>No of Students Registered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Notes__c</fullName>
        <description>Notes provided by the consultant</description>
        <label>Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Selected_Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Selected Course</label>
        <referenceTo>hed__Course_Offering__c</referenceTo>
        <relationshipLabel>Slots</relationshipLabel>
        <relationshipName>Slots</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>In Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>MultiselectPicklist</type>
    </fields><fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>175</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed by Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Appointments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Slot</label><nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Coach Availability Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Slots</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Counselor_Availability_Definition__c.object
<CustomObject><fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Consultant. Need to link this to Contact to allow them having Write access</description>
        <label>Consultant</label>
        <referenceTo>Consultant__c</referenceTo>
        <relationshipLabel>Availability</relationshipLabel>
        <relationshipName>Availability</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Availability</label><nameField>
        <displayFormat>CAD-{0000}</displayFormat>
        <label>Coach Availability Definition Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Availability</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Read</sharingModel></CustomObject>

objects/hed__Course_Offering__c.object
<CustomObject><fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Tutoring</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SI Session</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLTL</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Course_Offering_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Joins Courses and Terms to contain information related to a single occurrence of a course.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Course Offering</label><nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField><pluralLabel>Course Offerings</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/USF_SlotDetailsConsultantExtn.cls
//************************************************************************************
// Name             : USF_SlotDetailsConsultantExtn
// Description      : Controller for USF_SlotDetailsConsultant Visualforce page
// Created By       : Mohan Kalagatla
// Created Date     : 08/25/2016
// ************************Version Updates********************************************
// Date             Developer           Description
// -----------------------------------------------------------------------------------
// 08/25/2016       Mohan Kalagatla       Created
// ************************************************************************************
public without sharing class USF_SlotDetailsConsultantExtn {

ApexPages.StandardController stdController {get; set;}
public Id slotId {get; set;}
public Id updateAppointmentId {get;set;}
public String updateAction {get;set;}
public String slotDate {get;set;}
public String slotTime {get;set;}
public String newLocation{get;set;}
public String newMaxStudents {get;set;}    
public String newNotes {get;set;}   
public String newMeetingNotes {get;set;}    
public String cancel {get; set;}
public String complete {get; set;}    
public boolean isLWCConsultant{get;set;} 
public Boolean isPermissionAssgined{get;set;}
public String checkin{get;set;}

//Added by Vandana - DFCT0011049
public Boolean hasACheckedInStudent{get;set;}
// Place holder for colors based on status
    public String confirm {get;set;}
    public String pending {get;set;}
    //public String cancel {get;set;}
    public String missed {get;set;}
    public String prevpageName {get;set;}
    //public String checkin {get;set;}
    //public String complete {get; set;}
//Modified by Vandana - DFCT0011069
public Boolean hasAppointments{get;set;}
public Boolean isModificationSuccessful{get;set;}

    // Constructor to perform initializations
    public USF_SlotDetailsConsultantExtn(ApexPages.StandardController controller){ 
        stdController = controller;
        slotId = ((Counsellor_Availability__c)stdController.getRecord()).Id;        
        cancel = App_Config__c.getInstance('Cancel').Text_Value__c;
        complete = App_Config__c.getInstance('Complete').Text_Value__c;
        isLWCConsultant = false;
        prevpageName = ApexPages.currentPage().getHeaders().get('Referer');
        System.debug('prevpageName '+prevpageName);

        //isPermissionAssgined=USF_PermissionSetAssignmentUtli.getPermissionSetFlag();
        //Modified by Vandana to remove permission set related functionality
        User currentUser = [Select Id, ContactId, AccountId FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        List<Consultant__c> activeConsultants = USF_DBUtil.getActiveConsultantsByContactId(currentUser.ContactId);
         
        //String usrProfileName = [select id, Profile.Name from User where id = :Userinfo.getUserId()].Profile.Name;     
        if(!activeConsultants.isEmpty()){
            isPermissionAssgined = true;
            isLWCConsultant=true;
        }
        //Added by Vandana - DFCT0011049
        hasACheckedInStudent = false;
        checkin = App_Config__c.getInstance('Check').Text_Value__c;
        getAppointments();
        System.debug('##hasACheckedInStudent: '+hasACheckedInStudent);
        confirm = App_Config__c.getInstance('Confirm').Text_Value__c; 
        pending = App_Config__c.getInstance('Pending').Text_Value__c; 
        //cancel = App_Config__c.getInstance('Cancel').Text_Value__c; 
        missed = App_Config__c.getInstance('Missed').Text_Value__c; 
        //checkin = App_Config__c.getInstance('Check').Text_Value__c; 
        //complete = App_Config__c.getInstance('Complete').Text_Value__c;
        hasAppointments = false;
        isModificationSuccessful = false;
    }
    
    // Get Slot
     public USF_SlotDTO getSlotDTO(){
      Counsellor_Availability__c slot = [Select Id,Type__c,Name,Start_Time__c,Coach_Full_Name__c,Status__c,Notes__c,Center__c,Capacity__c,Noofstudentsregistered__c,Selected_Course__r.Name,
                 Location__c,AppointmentType__c from Counsellor_Availability__c where Id = :slotId LIMIT 1];
         
          USF_SlotDTO slotDTO =  new USF_SlotDTO(slot,slot.Start_Time__c.format('EEEE, MMM d yyyy'),slot.Start_Time__c.format('hh:mm a'));
          newLocation = slot.Location__c;
          newMaxStudents = String.valueOf(slot.Capacity__c);
          newNotes = slot.Notes__c;
          newMeetingNotes = slot.Notes__c;
          if(String.valueOf(slot.Noofstudentsregistered__c)!='' && slot.Noofstudentsregistered__c!=0 && slot.Noofstudentsregistered__c>0){
                hasAppointments = true;
          }
      return slotDTO;                
    }
        
    //Get List of Appointments
    public List<AppointmentContact__c> getAppointments(){
        List<AppointmentContact__c> appointmentList = new List<AppointmentContact__c>();
            if(slotId!=null){
                appointmentList = [SELECT Id,Status__c,Contact__r.Name,Contact__r.Preferred_Name__c,Contact__r.Academic_Success_Coach__c,Contact__r.CWID__c,
                                            Contact__r.Phone,Contact__r.Expected_Graduation_Term__r.Name,Contact__r.Email,Contact__r.Department,Contact__r.PhotoUrl,Contact__r.Photo__c,
                                            (SELECT Id,Name FROM Attachments)                  
                                    FROM  AppointmentContact__c 
                                    WHERE AppointmentSlot__c = :slotId
                                    ORDER BY Start_Time__c asc];
            }
            //Added by Vandana - DFCT0011049
            for(AppointmentContact__c appt:appointmentList){
                if(appt.status__c.containsIgnoreCase(App_Config__c.getInstance('Student Checkin by Consultant').Text_Value__c)){
                     hasACheckedInStudent = true;
                 }else{
                     continue;
                 }
            }
            
            return appointmentList;                
    }
    
    // Get Location picklist values   
     public List<SelectOption> getLocation(){     
        List<SelectOption> options = new List<SelectOption>();     
        //options.add(new SelectOption('0001','-Select-'));
        Schema.DescribeFieldResult fieldResult = Counselor_Availability_Definition__c.Location__c.getDescribe();
        if(fieldResult!=null){
        for(Schema.PicklistEntry p : fieldResult.getPicklistValues()){
        options.add(new SelectOption(p.getValue(), p.getValue()));   
        }
        }
        return options;
    }    
          
    // Update Appointment status
    public void updateAppointmentStatus(){                      
           try{
                AppointmentContact__c updateAppointment = new AppointmentContact__c();
                if(updateAppointmentId != null){                        
                  updateAppointment.id=updateAppointmentId;
                     if(updateAction =='Missed by Student'&& updateAppointment.Status__c != App_Config__c.getInstance('Missed By Student').Text_Value__c){
                        updateAppointment.Status__c = App_Config__c.getInstance('Missed By Student').Text_Value__c;
                     }
                     else if(updateAction =='Check In Student' && updateAppointment.Status__c != App_Config__c.getInstance('Student Checkin by Consultant').Text_Value__c){                       
                        updateAppointment.Status__c = App_Config__c.getInstance('Student Checkin by Consultant').Text_Value__c;
                     }
                      if(updateAppointment!=null){   
                        update updateAppointment;
                      }
                  }
            }   
            catch(Exception ex){
                // Display the error message
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
            }
    }
          
    // Update Slot status to Completed
    public void markCompleted(){   
          try{
             Counsellor_Availability__c slot = new Counsellor_Availability__c();
              if(slotId!=null){    
                    slot.id=slotId;
                    if(slot.Status__c != App_Config__c.getInstance('LWC Slot Complete Status').Text_Value__c){
                            slot.Status__c = App_Config__c.getInstance('LWC Slot Complete Status').Text_Value__c;  
                             if(slot.Notes__c != newNotes){
                                 slot.Notes__c = newNotes;      
                             } 
                        if(slot!=null){     
                          update slot;   
                        }  
                    }
            }
          }
          catch(Exception ex){
             // Display the error message
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));                          
          } 
    }
    
    // Save notes on Slot record
    public void saveNotes(){              
            try{             
               Counsellor_Availability__c slot = new Counsellor_Availability__c();
               if(slotId!=null){    
                    slot.id=slotId;
                    if(slot.Notes__c!=newMeetingNotes){
                        slot.Notes__c = newMeetingNotes; 
                        if(slot!=null){                     
                          update slot;
                        }
                    }
                 }
            }
            catch(Exception ex){
                // Display the error message
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
            }
    }
    
    // Update location and Max students on Slot record
    public void modifySlot()
    {
            try {
                isModificationSuccessful = false;
               Counsellor_Availability__c slot = new Counsellor_Availability__c();
               if(slotId!=null){    
                    slot.id=slotId;
                    if(slot.Location__c != newlocation || slot.Capacity__c != Decimal.valueOf(newMaxStudents)){
                        if(slot.Location__c != newlocation){
                            slot.Location__c = newlocation;
                        }
                        if(slot.Capacity__c != Decimal.valueOf(newMaxStudents)){
                            slot.Capacity__c = Decimal.valueOf(newMaxStudents);
                        }    
                        if(slot!=null){                
                         update slot;
                         isModificationSuccessful = true;
                        }
                    }
                 }
            }   
            catch(Exception ex){
                // Display the error message
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
            }  
    }
   
   // Cancel Slot record
    public void cancelSlot() {
            try {
               Counsellor_Availability__c slot = new Counsellor_Availability__c();
               if(slotId!=null){    
                slot.id=slotId;
                if(slot!= null && slot.Status__c != App_Config__c.getInstance('Slot Cancelled Status').Text_Value__c){
                        slot.Status__c = App_Config__c.getInstance('Slot Cancelled Status').Text_Value__c;
                        if(slot!=null){
                          update slot;
                        }
                }
               }
            }     
            catch(Exception ex){
                // Display the error message
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
            }
    }
    
    public PageReference redirectBack() {
      PageReference retURL = new PageReference(prevpageName);
      retURL.setRedirect(true);
      return retURL;
    }
}