objects/App_Config__c.object
<CustomObject><fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <type>TextArea</type>
    </fields><customSettingsType>List</customSettingsType><description>Stores all configurable settings for USF</description><enableFeeds>false</enableFeeds><label>App Config</label><visibility>Public</visibility></CustomObject>

objects/AppointmentContact__c.object
<CustomObject><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Appointments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Notes</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Appointment</label><nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Appointments</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

classes/USF_AppointmentDTO.cls
/************************************************************************************
// Name             : USF_AppointmentDTO
// Description      : Wrapper class for Appointment 
// Created By       : Ankit Jain
// Created Date     : 09/09/2016
// ************************Version Updates********************************************
// Date             Developer           Description
// -----------------------------------------------------------------------------------
// 09/09/2016       Ankit Jain       Created
// ************************************************************************************/

public class USF_AppointmentDTO{
        public AppointmentContact__c appointment {get;set;}
        public String startdate {get;set;}
        public String starttime {get;set;}
        public String colorClass {get;set;}
        public String statusToDisplay {get;set;}
        public String statuSymbolClass {get;set;}
        public USF_AppointmentDTO(AppointmentContact__c appointment, String starttime){
            this.appointment = appointment;
            this.starttime = starttime;
            if(appointment.Status__c!=null){
                if(appointment.Status__c.contains(App_Config__c.getInstance('Confirm').Text_Value__c)){
                    colorClass = 'confirm';
                    statusToDisplay = appointment.Status__c.touppercase();
                    statuSymbolClass = 'glyphicon glyphicon-ok';
                }
                else if(appointment.Status__c.contains(App_Config__c.getInstance('Pending').Text_Value__c)){
                    colorClass = 'pending';
                    statusToDisplay = appointment.Status__c.touppercase()+' . . .';
                    statuSymbolClass = 'test';
                }
                else if(appointment.Status__c.contains(App_Config__c.getInstance('Cancel').Text_Value__c)){
                    colorClass = 'cancel';
                    statusToDisplay = appointment.Status__c.touppercase();
                    statuSymbolClass = 'glyphicon glyphicon-remove';
                }
                else if(appointment.Status__c.contains(App_Config__c.getInstance('Missed').Text_Value__c)){
                    colorClass = 'missed';
                    statusToDisplay = appointment.Status__c.touppercase()+' !';
                    statuSymbolClass = 'test';
                }
                else if(appointment.Status__c.contains(App_Config__c.getInstance('Check').Text_Value__c)){
                    colorClass = 'checkin';
                    statusToDisplay = appointment.Status__c.touppercase();
                    statuSymbolClass = 'glyphicon glyphicon-ok';
                }
                else{
                    colorClass = 'pending';
                    statusToDisplay = appointment.Status__c.touppercase();
                    statuSymbolClass = 'test';
                }  
            }     
        }
        
         public USF_AppointmentDTO(AppointmentContact__c appointment,String startdate,String starttime){
            this.appointment = appointment;
            this.startdate = startdate;
            this.starttime = starttime;
            if(appointment.Status__c!=null){
                if(appointment.Status__c.contains(App_Config__c.getInstance('Confirm').Text_Value__c)){
                    colorClass = 'confirm';
                    statusToDisplay = appointment.Status__c.touppercase();
                    statuSymbolClass = 'glyphicon glyphicon-ok';
                }
                else if(appointment.Status__c.contains(App_Config__c.getInstance('Pending').Text_Value__c)){
                    colorClass = 'pending';
                    statusToDisplay = appointment.Status__c.touppercase()+' . . .';
                    statuSymbolClass = 'test';
                }
                else if(appointment.Status__c.contains(App_Config__c.getInstance('Cancel').Text_Value__c)){
                    colorClass = 'cancel';
                    statusToDisplay = appointment.Status__c.touppercase();
                    statuSymbolClass = 'glyphicon glyphicon-remove';
                }
                else if(appointment.Status__c.contains(App_Config__c.getInstance('Missed').Text_Value__c)){
                    colorClass = 'missed';
                    statusToDisplay = appointment.Status__c.touppercase()+' !';
                    statuSymbolClass = 'test';
                }
                else if(appointment.Status__c.contains(App_Config__c.getInstance('Check').Text_Value__c)){
                    colorClass = 'checkin';
                    statusToDisplay = appointment.Status__c.touppercase();
                    statuSymbolClass = 'glyphicon glyphicon-ok';
                }
                else{
                    colorClass = 'pending';
                    statusToDisplay = appointment.Status__c.touppercase();
                    statuSymbolClass = 'test';
                }  
            }     
        }
    }