objects/App_Config__c.object
<CustomObject><fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <type>TextArea</type>
    </fields><customSettingsType>List</customSettingsType><description>Stores all configurable settings for USF</description><enableFeeds>false</enableFeeds><label>App Config</label><visibility>Public</visibility></CustomObject>

objects/AppointmentContact__c.object
<CustomObject><fields>
        <fullName>Date_Time__c</fullName>
        <formula>AppointmentSlot__r.Start_Time__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date/Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Appointments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Notes</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Appointment</label><nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Appointments</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel><recordTypes>
        <fullName>CASA_Appointment</fullName>
        <active>true</active>
        <label>CASA Appointment</label>
    </recordTypes></CustomObject>

objects/Counsellor_Availability__c.object
<CustomObject><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed by Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Appointments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Slot</label><nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Coach Availability Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Slots</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Counselor_Availability_Definition__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Availability</label><nameField>
        <displayFormat>CAD-{0000}</displayFormat>
        <label>Coach Availability Definition Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Availability</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Read</sharingModel></CustomObject>

classes/USF_FrontDeskDashboardControllerTest.cls
/** Class Name   : USF_FrontDeskDashboardControllerTest
 *  Description  : Test Class for USF_FacultyStaffEAPFormController
 *  Created By   : Ankit Jain
 *  Created On   : 5-Oct-2016
 *  Modification Log:
   ------------------------------------------------------------------------------------
   Developer                       Date                Description
   ------------------------------------------------------------------------------------
   Ankit Jain                     5-Oct-2016          Original Version
 */
@isTest
public with sharing class USF_FrontDeskDashboardControllerTest{
    @isTest
    static void TestUSF_FrontDeskDashboardController(){
        
        User usr = Test_Utility.createTestUser('testusername','System Administrator');
        if(usr!=null)
            insert usr;
        System.runAs(usr){ 
            List<App_Config__c> appConfigList = new List<App_Config__c>();  
            App_Config__c appConfig = Test_Utility.createAppConfig('CASA Dashboard Today Value','TODAY');
            if(appConfig!=null)
                appConfigList.add(appConfig);   
            App_Config__c appConfig2 = Test_Utility.createAppConfig('Default CASA status filter','All Appointments');
            if(appConfig2!=null)
                appConfigList.add(appConfig2); 
            App_Config__c appConfig3 = Test_Utility.createAppConfig('Default CASA Coach filter','CASA Staff');
            if(appConfig3!=null)
                appConfigList.add(appConfig3);  
            App_Config__c appConfig4 = Test_Utility.createAppConfig('Dropin Appointment','Drop In');
            if(appConfig4!=null)
                appConfigList.add(appConfig4); 
            if(appConfigList!= null && appConfigList.size()>0)
                insert appConfigList ;  
            List<App_Config__c> configList = Test_Utility.createAppConfigList();
                insert configList;
            Account acc = Test_Utility.createAccount();
            if(acc!=null)
                insert acc;
            List<Contact> conList = Test_Utility.createContact(1,usr.id,true,acc.id);
            if(conList!=null && conList.size()>0)
                insert conList; 
            BusinessHours bhs = [select id from BusinessHours where IsDefault=true];    
            DateTime startTime = BusinessHours.nextStartDate(bhs.id, System.now());
            List<Counselor_Availability_Definition__c> availList = new List<Counselor_Availability_Definition__c>();
            availList.add(Test_Utility.createAvailability(acc.Id,startTime));
            //availList.add(Test_Utility.createAvailability(acc.Id,System.now().time()));    
            insert availList;
                
            Counsellor_Availability__c slot = Test_Utility.createSlot(availList[0].id);    
                insert slot;
            // Event is required for Process builder - USF Create/Update Event for Pending/Confirmed CASA Appointment    
            Event evnt = Test_Utility.createEvent(slot.id);
                insert evnt;  
            List<AppointmentContact__c> appList = Test_Utility.createAppointmentContact(2,'CASA_Appointment',conList[0].id,slot.id);
            if(!appList.isEmpty()){
                //appList[1].status__c = 'Missed';
                //appList[2].status__c = 'Confirm';
                appList[1].status__c = 'Checked-In';
                insert appList;
                System.debug('rectype'+appList[0].recordtypeid);
                System.debug('stats'+appList[1].status__c);
                System.debug('Date_Timec'+appList[1].Date_Time__c);
            }
            Test.startTest();
            USF_FrontDeskDashboardController fddc = new USF_FrontDeskDashboardController();
            /*List<USF_AppointmentDTO> appDtoList = fddc.getAppoinitmentRecords();
            System.assert(appDtoList.size()>0);
            List<SelectOption> options = fddc.getTodayFilterValues();
            System.assertEquals(4,options.size());
            List<SelectOption> option2 = fddc.getCoachFilterValues();
            System.assert(option2.size()>0);
            fddc.selectedAction = App_Config__c.getInstance('Checkin').Text_Value__c;
            fddc.updateStatusField();
            fddc.selectedAction = App_Config__c.getInstance('Confirm').Text_Value__c;
            fddc.updateStatusField();
            fddc.selectedAction = App_Config__c.getInstance('Missed').Text_Value__c;
            fddc.updateStatusField();
            fddc.selectedAction = App_Config__c.getInstance('Complete').Text_Value__c;
            fddc.updateStatusField();
            fddc.getLatestCheckedInStudent();*/
            Test.stopTest();    
        }   
                         
    }
    
}