objects/App_Config__c.object
<CustomObject><fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <type>TextArea</type>
    </fields><customSettingsType>List</customSettingsType><description>Stores all configurable settings for USF</description><enableFeeds>false</enableFeeds><label>App Config</label><visibility>Public</visibility></CustomObject>

objects/AppointmentContact__c.object
<CustomObject><fields>
        <fullName>AppointmentSlot__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Appointment Slot</label>
        <referenceTo>Counsellor_Availability__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointment_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Center__c</fullName>
        <inlineHelpText>This field will get updated by the workflow on creation of the appointment</inlineHelpText>
        <label>Center</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Coach_Specialty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coach Specialty</label>
        <referenceTo>Specialty__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointment_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Date_Time__c</fullName>
        <formula>AppointmentSlot__r.Start_Time__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date/Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>LWC_LearningStyles__c</fullName>
        <label>Learning Styles</label>
        <picklist>
            <picklistValues>
                <fullName>Visual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kinesthetic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auditory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read/Write</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Notes__c</fullName>
        <description>Notes provided by the student during appointment scheduling (LWC)</description>
        <label>Background Notes (Visible to Students)</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Phone__c</fullName>
        <description>Student Phone from Banner</description>
        <formula>Contact__r.Phone</formula>
        <inlineHelpText>Student Phone from Banner</inlineHelpText>
        <label>Phone</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Preferred_Phone__c</fullName>
        <inlineHelpText>Phone received from the student when booking an appointment</inlineHelpText>
        <label>Preferred Phone</label>
        <type>Phone</type>
    </fields><fields>
        <fullName>Reason_for_Meeting__c</fullName>
        <label>Appointment Reasons</label>
        <picklist>
            <picklistValues>
                <fullName>Academic Coaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Probation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Concerns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housing / Residence Hall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leave of Absence / Withdrawal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Concerns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major / Minor Exploration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Study Abroad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Student Survey</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields>
        <fullName>Referred_By__c</fullName>
        <label>Referred By</label>
        <picklist>
            <picklistValues>
                <fullName>Faculty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent / Guardian</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields>
        <fullName>Referrer_Name__c</fullName>
        <label>Referrer Name</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>SelectedCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>hed__Course_Offering__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Start_Time__c</fullName>
        <formula>IF(
  OR(
    VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) = 0,
    VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) = 12
  ),
  "12",
  TEXT( VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) 
   -
   IF( 
     VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) &lt; 12, 
     0, 
     12 
   ) 
  )
)
&amp; ":" &amp;
MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 15, 2 )
&amp; " " &amp;
IF(
  VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) &lt; 12,
  "AM",
  "PM"
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Time</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>175</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Appointments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Notes</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>In Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone/Online</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Appointment</label><nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Appointments</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Counsellor_Availability__c.object
<CustomObject><fields>
        <fullName>Center__c</fullName>
        <formula>Availability__r.Success_Center__r.Name</formula>
        <label>Center</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Coach_Full_Name__c</fullName>
        <description>FirstName LastName</description>
        <formula>Coach_First_Name__c &amp; " " &amp;  Coach_Last_Name__c</formula>
        <label>Coach Full Name</label>
        <type>Text</type>
    </fields><fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Notes__c</fullName>
        <description>Notes provided by the consultant</description>
        <label>Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>In Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>MultiselectPicklist</type>
    </fields><fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>175</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed by Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Appointments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Slot</label><nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Coach Availability Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Slots</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/hed__Course_Offering__c.object
<CustomObject><fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Tutoring</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SI Session</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLTL</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Course_Offering_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Joins Courses and Terms to contain information related to a single occurrence of a course.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Course Offering</label><nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField><pluralLabel>Course Offerings</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Specialty__c.object
<CustomObject><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Specialty</label><nameField>
        <label>Specialty Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Specialties</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/USF_ModifyLWCAppointmentExtn.cls
//************************************************************************************
// Name             : USF_ModifyLWCAppointmentExtn
// Description      : Contoller to USF_ModifyLWCAppointment Visualforce page
// Created By       : Mohan Kalagatla
// Created Date     : 08/25/2016 
// ************************Version Updates********************************************
// Date             Developer           Description
// -----------------------------------------------------------------------------------
// 08/25/2016        Mohan Kalagatla       Created
// ************************************************************************************
public with sharing class USF_ModifyLWCAppointmentExtn {
    ApexPages.StandardController stdController {get; set;}
    public Id appointmentId {get; set;}
    public String fileName {get;set;}
    public Blob fileBody{get;set;}
    public String newType{get;set;}
    public String newPhone{get;set;}
    public String newNotes{get;set;}
    public Boolean disableNotes{get;set;}
    public Boolean isLearning{get;set;}
    public Boolean isWriting{get;set;}
    public Boolean isSpeaking{get;set;}
    public List<Attachment> allCurrentAttachments{get;set;}
    public String attachmentIdsToBeRemoved{get;set;}
    public Attachment attachment { 
        get {
          if (attachment == null)
            attachment = new Attachment();
          return attachment;
        }
        set;}
    
    // Counstuctor for initializations
    public USF_ModifyLWCAppointmentExtn(ApexPages.StandardController controller){
        isLearning = false;
        isWriting = false;
        isSpeaking = false;
        disableNotes = false;
        attachmentIdsToBeRemoved = '';
        stdController = controller;
        appointmentId = ((AppointmentContact__c)stdController.getRecord()).Id; 
        allCurrentAttachments = new List<Attachment>();
        AppointmentContact__c  appointment = [SELECT Id,(SELECT Id,Name FROM Attachments) FROM AppointmentContact__c WHERE Id=:appointmentId];
        allCurrentAttachments = appointment.Attachments;
    }
    
    // Get Appointment
    public USF_AppointmentDTO getAppDTO(){
         AppointmentContact__c  appointment = [SELECT Id,Status__c,Reason_for_Meeting__c,Notes__c,Phone__c,Referred_By__c,Referrer_Name__c,Date_Time__c,
                        Type__c,SelectedCourse__r.Name,Contact__r.id,AppointmentSlot__r.Name,AppointmentSlot__r.Location__c,Center__c,
                        AppointmentSlot__r.Type__c,AppointmentSlot__r.Coach_Full_Name__c,AppointmentSlot__r.Start_Time__c,
                        AppointmentSlot__r.End_Time__c,Coach_Specialty__r.Name,LWC_LearningStyles__c,Preferred_Phone__c,(SELECT Id,Name FROM Attachments)
                        FROM AppointmentContact__c WHERE Id=:appointmentId]; 
         newType = appointment.Type__c;
         newPhone = appointment.Preferred_Phone__c;
         newNotes = appointment.Notes__c;
         
         DateTime currentTime = DateTime.now();
        if(currentTime > appointment.AppointmentSlot__r.Start_Time__c){
           disableNotes = true;
        }
         allCurrentAttachments = new List<Attachment>();
         allCurrentAttachments = appointment.Attachments;
         System.debug('allCurrentAttachments: '+allCurrentAttachments);
         if(appointment.Center__c.contains(App_Config__c.getInstance('Learning Center').Text_Value__c)){
            isLearning = true;
         }else if(appointment.Center__c.contains(App_Config__c.getInstance('Speaking Center').Text_Value__c)){
            isSpeaking = true;
         }else if(appointment.Center__c.contains(App_Config__c.getInstance('Writing Center').Text_Value__c)){
            isWriting = true;
         }
         System.debug('isLearning'+isLearning);
         System.debug('isWriting'+isWriting);
         System.debug('isSpeaking'+isSpeaking);
         
         USF_AppointmentDTO appDTO = new USF_AppointmentDTO(appointment,appointment.AppointmentSlot__r.Start_Time__c.format('d MMMM yyyy'),appointment.AppointmentSlot__r.Start_Time__c.format('hh:mm a')+' - '+appointment.AppointmentSlot__r.End_Time__c.format('hh:mm a'));
         return appDTO;     
    }
    
    // Get Type picklist values   
     public List<SelectOption> getType(){     
        List<SelectOption> options = new List<SelectOption>();     
        options.add(new SelectOption('','-None-'));
        Schema.DescribeFieldResult fieldResult = AppointmentContact__c.Type__c.getDescribe();
        if(fieldResult!=null){
        for(Schema.PicklistEntry p : fieldResult.getPicklistValues()){
        options.add(new SelectOption(p.getValue(), p.getValue()));   
        }
        }
        return options;
    }    
    
    //  Method to save Appointment record and return to USF_ModifyLWCAppointmentConfirmation VF page
    public PageReference modifyAppointment(){ 
        try{  
            AppointmentContact__c appointment = new AppointmentContact__c();  
            if(appointmentId!=null){
                appointment.id=appointmentId;
               /*  if(fileBody != null && fileName != null){
                      Attachment myAttachment  = new Attachment();
                      myAttachment.Body = fileBody;
                      myAttachment.Name = fileName;
                      myAttachment.ParentId = appointmentId;
                      insert myAttachment;
                 } */
                 
                 if(appointment.Type__c!=newType) 
                    appointment.Type__c = newType;
                 if(appointment.Preferred_Phone__c != newPhone)   
                    appointment.Preferred_Phone__c = newPhone;    
                 if(appointment.Notes__c != newNotes)     
                    appointment.Notes__c = newNotes;            
                    if(appointment!=null){  
                        update appointment;   
                    }  
             }
                deleteAttachments();
                PageReference pageRef = Page.USF_ModifyLWCAppointmentConfirmation;
                pageRef.getParameters().put('Id',appointmentId);
                pageRef.setRedirect(true);
                return pageRef; 
                
        }        
        catch(Exception ex){
                // Display the error message
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
                return null;
        }
     }
     
     public void deleteAttachments(){
        try{
            System.debug('attachmentIdsToBeRemoved**'+attachmentIdsToBeRemoved);
            List<String> allAttachmentIds = new List<String>();
            allAttachmentIds = attachmentIdsToBeRemoved.split(';');
            List<Attachment> finalAttachmentsDelete = new List<Attachment>();
            finalAttachmentsDelete = [Select Id FROM Attachment WHERE Id IN :allAttachmentIds];
            if(!finalAttachmentsDelete.isEmpty()){
                delete finalAttachmentsDelete;
            }
        }catch(Exception ex){
                // Display the error message
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
        }
        
     }   
}