objects/App_Config__c.object
<CustomObject><fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <type>TextArea</type>
    </fields><customSettingsType>List</customSettingsType><description>Stores all configurable settings for USF</description><enableFeeds>false</enableFeeds><label>App Config</label><visibility>Public</visibility></CustomObject>

objects/AppointmentContact__c.object
<CustomObject><fields>
        <fullName>AppointmentSlot__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Appointment Slot</label>
        <referenceTo>Counsellor_Availability__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointment_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><fields>
        <fullName>CWID__c</fullName>
        <formula>Contact__r.CWID__c</formula>
        <label>CWID</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Canceled_Date_Time__c</fullName>
        <description>Captures time stamp when the appointment has been cancelled</description>
        <label>Canceled Date/Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Center__c</fullName>
        <inlineHelpText>This field will get updated by the workflow on creation of the appointment</inlineHelpText>
        <label>Center</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointment_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Date_Time__c</fullName>
        <formula>AppointmentSlot__r.Start_Time__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date/Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Reason_for_Meeting__c</fullName>
        <label>Appointment Reasons</label>
        <picklist>
            <picklistValues>
                <fullName>Academic Coaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Probation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Concerns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housing / Residence Hall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leave of Absence / Withdrawal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Concerns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major / Minor Exploration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Study Abroad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Student Survey</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields>
        <fullName>Staff__c</fullName>
        <description>Supports the email template functionality (CASA and LWCl)</description>
        <formula>AppointmentSlot__r.Coach_Full_Name__c</formula>
        <label>Staff</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Start_Date__c</fullName>
        <formula>AppointmentSlot__r.StartDate__c</formula>
        <label>Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Start_Time__c</fullName>
        <formula>IF(
  OR(
    VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) = 0,
    VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) = 12
  ),
  "12",
  TEXT( VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) 
   -
   IF( 
     VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) &lt; 12, 
     0, 
     12 
   ) 
  )
)
&amp; ":" &amp;
MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 15, 2 )
&amp; " " &amp;
IF(
  VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) &lt; 12,
  "AM",
  "PM"
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Time</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Appointments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Notes</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Strike__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Strike</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Appointment</label><nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Appointments</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Contact.object
<CustomObject><fields>
        <fullName>AcademicSuccessCoach__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Academic Success Coach</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notEqual</operation>
                <value>Customer Community User</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>CWID__c</fullName>
        <description>The primary USF ID</description>
        <externalId>true</externalId>
        <label>CWID</label>
        <length>100</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Number_of_Units_in_Current_Term__c</fullName>
        <label>Number of Units in Current Term</label>
        <precision>3</precision>
        <scale>0</scale>
        
        <type>Number</type>
    </fields><fields>
        <fullName>Reason_Withdrawn__c</fullName>
        <label>Reason Withdrawn</label>
        <length>255</length>
        
        <type>Text</type>
    </fields><fields>
        <fullName>Staff__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to identify a member of USF Staff for integration purposes.</description>
        <label>Staff</label>
        <type>Checkbox</type>
    </fields><compactLayoutAssignment>hed__HEDA_Contact_Compact_Layout</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Counsellor_Availability__c.object
<CustomObject><fields>
        <fullName>Availability__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used to store the reference to Availability</description>
        <label>Availability</label>
        <referenceTo>Counselor_Availability_Definition__c</referenceTo>
        <relationshipLabel>Slots (Availability)</relationshipLabel>
        <relationshipName>Slots</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Center__c</fullName>
        <formula>Availability__r.Success_Center__r.Name</formula>
        <label>Center</label>
        <type>Text</type>
    </fields><fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed by Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Appointments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Slot</label><nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Coach Availability Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Slots</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Counselor_Availability_Definition__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Availability</label><nameField>
        <displayFormat>CAD-{0000}</displayFormat>
        <label>Coach Availability Definition Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Availability</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Read</sharingModel></CustomObject>

objects/User.object
<CustomObject><fields>
        <fullName>User_Type__c</fullName>
        <label>User Type</label>
        <picklist>
            <picklistValues>
                <fullName>ASC</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><externalSharingModel>Read</externalSharingModel><sharingModel>Read</sharingModel></CustomObject>

classes/USF_FrontDeskDashboardController.cls
/************************************************************************************
// Name             : USF_FrontDeskDashboardController
// Description      : Controller for USF_FrontDeskStaffDashboard Visualforce page
// Created By       : Manjunath Singh
// Created Date     : 09/07/2016
// ************************Version Updates********************************************
// Date             Developer           Description
// -----------------------------------------------------------------------------------
// 09/07/2016       Manjunath Singh       Created
// ************************************************************************************/

public with sharing class USF_FrontDeskDashboardController{

    public List<USF_AppointmentDTO> appDTOList {get;set;}
    public USF_AppointmentDTO latestCheckedAppDTO {get;set;}
    public Integer upcomingCount {get;set;}
    public Integer pendingCount {get;set;}
    public Integer completeCount {get;set;}
    public Integer delayedCount {get;set;}
    public List<AppointmentContact__c> latestCheckedApp = new list<AppointmentContact__c>();
    
    //Variables to hold the filter Selects-Start
    public String selectedTodayValue {get;set;}
    public String selectedStatusValue {get;set;}
    public String selectedCoachValue {get;set;}
    //Variables to hold the filter Selects-End
    
    //Variables to Build Dynamic SOQL-Start
    public String query {get;set;}
    public String statusfilterCondition {get;set;}
    public String dateCoachfilterCondition {get;set;}
    //Variables to Build Dynamic SOQL-End
    
    public String selectedRecordId {get;set;}
    public String selectedAction {get;set;}
    public String systemToday;
    
    //Constructor
    public USF_FrontDeskDashboardController(){
        
        statusfilterCondition='';
        selectedTodayValue=App_Config__c.getInstance('CASA Dashboard Next 7 days Value').Text_Value__c;
        selectedStatusValue=App_Config__c.getInstance('Default CASA status filter').Text_Value__c;
        selectedCoachValue=App_Config__c.getInstance('Default CASA Coach filter').Text_Value__c;
        dateCoachfilterCondition =' AND (Start_Date__c=NEXT_N_DAYS:7 OR Start_Date__c=TODAY)';
        
        query='Select Contact__r.name ,Staff__c,Contact__r.AcademicSuccessCoach__r.Name,Canceled_Date_Time__c,Start_Time__c,CWID__c,Date_Time__c,Reason_for_Meeting__c,Status__c,lastmodifieddate from AppointmentContact__c WHERE Recordtype.name=\'CASA Appointment\'';
             
    }
    
    /**************************************************************
    Description: This method is used to populate appointments table
    Return type: List<USF_AppointmentDTO>
    Parameters: None
    Created By: Manjunath Singh
    ***************************************************************/
    public List<USF_AppointmentDTO> getAppoinitmentRecords(){
    
        upcomingCount = 0;
        pendingCount = 0;
        completeCount = 0;
        delayedCount  =0;
        statusfilterCondition='';
        
        getLatestCheckedInStudent();
    
    
        appDTOList = new List<USF_AppointmentDTO>();
    
        DateTime now = DateTime.now();
     if(selectedTodayValue !=null && selectedTodayValue !=''){
        //Coomented 31 Oct
        /*System.debug('selectedTodayValue...'+selectedTodayValue);
        if(selectedTodayValue.containsIgnoreCase('NEXT_N_DAYS')){     
        //dateCoachfilterCondition =' AND (start_date__c='+selectedTodayValue+' OR Start_Date__c = TODAY) ';
            dateCoachfilterCondition =' AND (start_date__c ='+selectedTodayValue +' OR (start_date__c > :now))';
            System.debug('dateCoachfilterCondition...'+dateCoachfilterCondition);
        }
        else{
        dateCoachfilterCondition =' AND start_date__c='+selectedTodayValue+'';
        }*/
         /*if(selectedTodayValue.equalsIgnoreCase('today')){ 
            dateCoachfilterCondition =' AND start_date__c='+selectedTodayValue+'';
        }
        else{
            dateCoachfilterCondition =' AND start_date__c='+selectedTodayValue+' AND start_date__c!=TODAY';
        }*/
        if(selectedTodayValue.containsIgnoreCase('NEXT_N_DAYS')){
            dateCoachfilterCondition =' AND (AppointmentSlot__r.End_Time__c ='+selectedTodayValue +' OR (AppointmentSlot__r.End_Time__c > :now AND start_date__c = TODAY))';
        }
        else if(selectedTodayValue.containsIgnoreCase('TODAY')){
            dateCoachfilterCondition =' AND (AppointmentSlot__r.End_Time__c > :now AND start_date__c = TODAY)';
        }
        else if(selectedTodayValue.containsIgnoreCase('YESTERDAY')){
            dateCoachfilterCondition =' AND ((AppointmentSlot__r.End_Time__c <= :now AND start_date__c = TODAY) OR start_date__c = YESTERDAY)';
        }
        else if(selectedTodayValue.containsIgnoreCase('LAST_N_DAYS')){
            dateCoachfilterCondition =' AND ((AppointmentSlot__r.End_Time__c <= :now AND start_date__c = TODAY) OR (start_date__c <= YESTERDAY AND AppointmentSlot__r.End_Time__c ='+selectedTodayValue+')) ';
        }
        else{
            dateCoachfilterCondition =' AND AppointmentSlot__r.End_Time__c='+selectedTodayValue+'';
        }
     }
     
     if(selectedStatusValue!=null && selectedStatusValue!='All Appointments'){
     
     statusfilterCondition=' AND Status__c=\''+selectedStatusValue+'\'';
     
     }
       
     if(selectedCoachValue!=App_Config__c.getInstance('Default CASA Coach filter').Text_Value__c){
     
     //dateCoachfilterCondition +=' AND Contact__r.AcademicSuccessCoach__c=\''+selectedCoachValue+'\'';
     dateCoachfilterCondition +=' AND AppointmentSlot__r.Availability__r.Coach__c=\''+selectedCoachValue+'\'';
     
     }

     List<AppointmentContact__c> appointments=Database.query(query+dateCoachfilterCondition+statusfilterCondition+' ORDER BY Date_Time__c asc LIMIT 1000');
        
        if(appointments.size()>0){
        for(AppointmentContact__c app:appointments ){
            
            USF_AppointmentDTO appDTO = new USF_AppointmentDTO(app,app.Date_Time__c.format('EEEE, MMM d yyyy,hh:mm a'));
            appDTOList.add(appDTO);
            
            // Calculating the values for Summary 
            if(app.status__c == App_Config__c.getInstance('CASA Appointment Confirmed Status').Text_Value__c){
                upcomingCount = upcomingCount +1;
               
            }
            
            if(app.status__c == App_Config__c.getInstance('CASA Appointment Cancelled Status').Text_Value__c)   {
            completeCount +=1;
            }
            
            if(app.status__c == App_Config__c.getInstance('CASA Appointment Pending Status').Text_Value__c)   {
            pendingCount +=1;
            }
        }
     }
         return appDTOList;
    
    }
    
   /****************************************************************
    Description: This method is used to populate today filter values
    Return type: List<SelectOption>
    Parameters: None
    Created By: Manjunath Singh
    ***************************************************************/ 
    public List<SelectOption> getTodayFilterValues()
    {
       List<SelectOption> options = new List<SelectOption>();
            
          options.add(new SelectOption('TODAY','Today'));
          options.add(new SelectOption('TOMORROW','Tomorrow'));
          options.add(new SelectOption('YESTERDAY','Yesterday'));
          options.add(new SelectOption('LAST_N_DAYS:7','Last 7 days'));
          options.add(new SelectOption('NEXT_N_DAYS:7','Next 7 days'));
           
       return options;
    }
    
    /****************************************************************
    Description: This method is used to populate Casa Staff filter values
    Return type: List<SelectOption>
    Parameters: None
    Created By: Manjunath Singh
    ***************************************************************/ 
    public List<SelectOption> getCoachFilterValues(){  
        
      List<SelectOption> options = new List<SelectOption>();
      options.add(new SelectOption(App_Config__c.getInstance('Default CASA Coach filter').Text_Value__c,App_Config__c.getInstance('Default CASA Coach filter').Text_Value__c));
        
    try{
        
      List<User> coachRecords=[Select id,name from user where user_type__c= :App_Config__c.getInstance('ASC User type').Text_Value__c and isActive=true Order By name asc]; 
    
     if(coachRecords.size()>0){
    
        for(User userRec:coachRecords){
             options.add(new SelectOption(userRec.id,userRec.name));
            }
    
           }
        }
   catch(Exception e){
   
       }  
            
    return options;
    }
    
    /****************************************************************
    Description: This method is used to update the status on actions
    Return type: Void
    Parameters: None
    Created By: Manjunath Singh
    ***************************************************************/ 

    public void updateStatusField(){
    
    AppointmentContact__c appointment=new AppointmentContact__c();
    
    if((selectedRecordId!=null && selectedRecordId!='')){
        
        appointment.id=selectedRecordId;
        
        if(selectedAction==App_Config__c.getInstance('Checkin').Text_Value__c){
        appointment.Status__c=App_Config__c.getInstance('Student Checkin by Consultant').Text_Value__c;
        }  
        else if(selectedAction==App_Config__c.getInstance('Complete').Text_Value__c){ 
        appointment.Status__c=App_Config__c.getInstance('LWC Slot Complete Status').Text_Value__c;
        }     
       /* else if(selectedAction==App_Config__c.getInstance('Missed').Text_Value__c){
        appointment.Status__c=App_Config__c.getInstance('USF_CASAAppointmentMissedStatus').Text_Value__c;
        }*/
        else if(selectedAction==App_Config__c.getInstance('Confirm').Text_Value__c){
        appointment.Status__c=App_Config__c.getInstance('LWC Appointment Confirmed Status').Text_Value__c;
        }
        
        try{
        update appointment;
        }
       catch(Exception e){
        
        }
    }    
    
    }
    
    
    /********************************************************************
    Description: This method is used to get the latest checked in student
    Return type: Void
    Parameters: None
    Created By: Manjunath Singh
    ********************************************************************/  
    
    public void getLatestCheckedInStudent(){
    
    try{
    DateTime now = DateTime.now();
    latestCheckedApp=[SELECT id,Contact__r.name,Staff__c, Contact__r.AcademicSuccessCoach__r.Name,Canceled_Date_Time__c,Start_Time__c,CWID__c,Date_Time__c,
                      Reason_for_Meeting__c,Status__c,lastmodifieddate 
                      from AppointmentContact__c where status__c=:App_Config__c.getInstance('Student Checkin by Consultant').Text_Value__c and Recordtype.developername=:App_Config__c.getInstance('CASA Appointment RecordType').Text_Value__c and Date_Time__c > :now order by Date_Time__c asc limit 1];
     if(latestCheckedApp.size()!=0){
           latestCheckedAppDTO = new USF_AppointmentDTO(latestCheckedApp[0], latestCheckedApp[0].Date_Time__c.format('hh:mm a'));
     }
    }
    catch(Exception e){
    
    }
    }
    
    /********************************************************************
    Description: This method is used for cancel appointment functionality
    Return type: PageReference
    Parameters: None
    Created By: Manjunath Singh
    ********************************************************************/
    public PageReference cancelAppointment() {

         List<AppointmentContact__c> appointments = [Select Id,RecordTypeId,
                                                    AppointmentSlot__r.Availability__r.Success_Center__r.Student_Missed_Per_Center__c,
                                                    Strike__c,Center__c,Date_Time__c,
                                                    Status__c
                                                    FROM AppointmentContact__c 
                                                    where Id =: selectedRecordId and Recordtype.developername=:App_Config__c.getInstance('CASA Appointment RecordType').Text_Value__c];
                                                                                           
        try {
                if(appointments[0] !=null && appointments[0].Status__c != App_Config__c.getInstance('CASA Appointment Cancelled Status').Text_Value__c){
                   appointments[0].Status__c = App_Config__c.getInstance('CASA Appointment Cancelled Status').Text_Value__c;    
                    update appointments[0];
                  }
             }
         catch(Exception e){
        
         }  
         
         return null;  
 }
    
    /********************************************************************8***************
    Description: This method is used to get status drop down values based on Record type
    Return type: AppointmentContact__c
    Parameters: None
    Created By: Manjunath Singh
    *************************************************************************************/
    public AppointmentContact__c dummyAppointment
    {
        get
        {
            if(dummyAppointment==null)
                dummyAppointment= new AppointmentContact__c();
                dummyAppointment.status__c=App_Config__c.getInstance('Default CASA status filter').Text_Value__c;
            return dummyAppointment;
        }
        set;
    }

}