objects/App_Config__c.object
<CustomObject><fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <type>TextArea</type>
    </fields><customSettingsType>List</customSettingsType><description>Stores all configurable settings for USF</description><enableFeeds>false</enableFeeds><label>App Config</label><visibility>Public</visibility></CustomObject>

objects/Consultant__c.object
<CustomObject><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Consultant</label><nameField>
        <label>Consultant Record Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Consultants</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/CommunitiesLandingController.cls
/**
 * An apex page controller that takes the user to the right start page based on credentials or lack thereof
 */
public with sharing class CommunitiesLandingController {
    
    // Code we will invoke on page load.
    public PageReference forwardToStartPage() {
        String startUrl = System.currentPageReference().getParameters().get('startURL');
        string communityName=App_Config__c.getInstance('CommunityName').name__c;
        Network community=[select id from Network where name=:communityName limit 1];
        String communityLoginURL=Network.getLoginUrl(community.id);
        String communityBaseURL=communityLoginURL.substring(0,communityLoginURL.lastIndexOf('/'));
        String customHomePage = communityBaseURL;
        Id profileId=userinfo.getProfileId();
        String profileName=[Select Id,Name from Profile where Id=:profileId].Name;
        User currentUser = [Select Id, ContactId, AccountId FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        List<Consultant__c> activeConsultants = USF_DBUtil.getActiveConsultantsByContactId(currentUser.ContactId);
        if(startUrl!=null){
        customHomePage=customHomePage+startUrl;
            return new PageReference(customHomePage); 
        }//Added by Vandana to remove permission set related functionality
        else if(!activeConsultants.isEmpty()){
        	System.debug('####Entered');
        	customHomePage=customHomePage+'/apex/USF_ConsultantDashboard';
            return new PageReference(customHomePage);
        }
        else if(profileName.equalsIgnoreCase(App_Config__c.getInstance('Student Profile Name').name__c)){
        	System.debug('####Student Profile');
            customHomePage=customHomePage+'/apex/USF_StudentDashboard';
            return new PageReference(customHomePage);
            
        }/*else if(profileName.equalsIgnoreCase(App_Config__c.getInstance('Consultant Profile Name').name__c)){
            customHomePage=customHomePage+'/apex/USF_ConsultantDashboard';
            return new PageReference(customHomePage);
        }*/        
        //Added by Manjunath-Start
        else if(profileName.equalsIgnoreCase(App_Config__c.getInstance('Faculty Profile Name').Text_Value__c)){
            customHomePage=customHomePage+'/apex/USF_FacultyDashBoard';
            return new PageReference(customHomePage);
            
        }
        
        //Added by Manjunath-End
        else{
                return Network.communitiesLanding();
        }
    }
    
    public CommunitiesLandingController() {}
}