objects/App_Config__c.object
<CustomObject><fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <type>TextArea</type>
    </fields><customSettingsType>List</customSettingsType><description>Stores all configurable settings for USF</description><enableFeeds>false</enableFeeds><label>App Config</label><visibility>Public</visibility></CustomObject>

classes/USF_StudentHelpFAQExtn.cls
public with sharing class USF_StudentHelpFAQExtn{
    
    public String FolderName{get;set;}
    public String FolderId{get;set;}
    public List<Document> allDocuments{get;set;}
    public USF_StudentHelpFAQExtn(){
        try{
            FolderName = App_Config__c.getValues('Document Folder Name for Student Help').Text_Value__c;
            FolderId = USF_DBUtil.getFolderIdByFolderName(FolderName);
            
            allDocuments = new List<Document>();
            allDocuments = USF_DBUtil.getDocumentsByFolderId(FolderId);
            System.debug('allDocuments***'+allDocuments);
            
        }catch(Exception e){
            System.debug('Exception: '+e.getMessage());
        }
    }
   
}