objects/App_Config__c.object
<CustomObject><fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <type>TextArea</type>
    </fields><customSettingsType>List</customSettingsType><description>Stores all configurable settings for USF</description><enableFeeds>false</enableFeeds><label>App Config</label><visibility>Public</visibility></CustomObject>

objects/AppointmentContact__c.object
<CustomObject><fields>
        <fullName>AppointmentSlot__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Appointment Slot</label>
        <referenceTo>Counsellor_Availability__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointment_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Start_Date__c</fullName>
        <formula>AppointmentSlot__r.StartDate__c</formula>
        <label>Start Date</label>
        <type>Date</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Appointment</label><nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Appointments</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Counsellor_Availability__c.object
<CustomObject><fields>
        <fullName>Availability__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used to store the reference to Availability</description>
        <label>Availability</label>
        <referenceTo>Counselor_Availability_Definition__c</referenceTo>
        <relationshipLabel>Slots (Availability)</relationshipLabel>
        <relationshipName>Slots</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Slot</label><nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Coach Availability Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Slots</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Counselor_Availability_Definition__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Availability</label><nameField>
        <displayFormat>CAD-{0000}</displayFormat>
        <label>Coach Availability Definition Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Availability</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Read</sharingModel></CustomObject>

classes/USF_NotificationController.cls
public class USF_NotificationController {
    Public list<AppointmentContact__Feed> lstAppFeed {get;set;}
    Public Set<ID> SetAppID {get;set;}
    Public string strPostType {get;set;}
    public list<wrapChatterPost> lstFinalChatterPost {get;set;}
    public list<wrapChatterPost> lstDisplayPost {get;set;}
    public String pageNameValue {get;set;}
    //Added by Vandana - DFCT0011042
    public String selectedCoachValue{get;set;}
    
    public USF_NotificationController(){
        
       /* getAppointmentID();
        if(!SetAppID.isEmpty()){
            getChatterPost();
        }*/
        //Added by Vandana - DFCT0011042
        selectedCoachValue = '';
    }
    
    public void getAppointmentID(){
        SetAppID= new set<ID>();
        string filterCondition='';
        //list<AppointmentContact__c> lstAppFeedDisplay=[select ID From AppointmentContact__c /*where Start_Date__c >=TODAY AND Start_Date__c<=TOMORROW*/];
        String query='select ID From AppointmentContact__c where Start_Date__c >=TODAY AND Start_Date__c<=TOMORROW ';
        if(String.isNotBlank(pageNameValue) && pageNameValue.equalsignorecase('casaDashboard')){
        filterCondition=' AND recordType.developername=\''+App_Config__c.getInstance('CASA Appointment RecordType').Text_Value__c+'\'';
        }
        else if(String.isNotBlank(pageNameValue) && pageNameValue.equalsignorecase('lwcDashboard')){
         filterCondition=' AND recordType.developername=\''+App_Config__c.getInstance('LWC Appointment RecordType').Text_Value__c+'\'';
        }
        
        //Added by Vandana - DFCT0011042 - start
        if(selectedCoachValue!='' && selectedCoachValue!= null && selectedCoachValue!=App_Config__c.getInstance('Default CASA Coach filter').Text_Value__c){
	     filterCondition +=' AND AppointmentSlot__r.Availability__r.Coach__c=\''+selectedCoachValue+'\'';
	    }
        //Added by Vandana - DFCT0011042 - end
        list<AppointmentContact__c> lstAppFeedDisplay=Database.query(query+filterCondition);
        system.debug('teststring:'+query+filterCondition);
        if(!lstAppFeedDisplay.isEmpty()){
            for(AppointmentContact__c toset:lstAppFeedDisplay){
                SetAppID.add(toset.ID);
            }
        }
    }
    public list<wrapChatterPost> getChatterPost(){
        getAppointmentID();
        lstDisplayPost= new list<wrapChatterPost>();
        if(!SetAppID.isEmpty()){
        
        lstFinalChatterPost= new list<wrapChatterPost>();
        lstAppFeed= new list<AppointmentContact__Feed>();
        lstAppFeed=[SELECT Body,CreatedDate, ParentId, Title FROM AppointmentContact__Feed WHERE Type = 'TextPost' AND ParentId IN:SetAppID ORDER BY CreatedDate DESC LIMIT 5];
        if(!lstAppFeed.isEmpty()){
            for(AppointmentContact__Feed feedpost: lstAppFeed){
                if(feedpost.Title=='Checked-In' ||feedpost.Title=='Update' ||feedpost.Title=='Missed' || feedpost.Title=='Cancelled'){
                    Datetime startDate = system.now();// Start date
                    Datetime endDate = feedpost.CreatedDate;//End Date               
                    long decHours = (((startDate.getTime())/1000/60-(endDate.getTime())/1000/60) );
                    long hours =decHours/60;
                    long minute= math.mod(decHours, 60);
                    if(hours>=24){
                        lstFinalChatterPost.add(new wrapChatterPost(feedpost.Title, feedpost.Body, 'On '+endDate ));
                    }
                    else if(hours<>0 && minute<>0){
                        lstFinalChatterPost.add(new wrapChatterPost(feedpost.Title, feedpost.Body, hours+' Hr '+ minute+' Minutes Ago'));
                    }
                    else if(hours==0 && minute==0){
                        lstFinalChatterPost.add(new wrapChatterPost(feedpost.Title, feedpost.Body, 'Just Now'));
                    }
                    else if(hours<>0 && minute==0){
                        lstFinalChatterPost.add(new wrapChatterPost(feedpost.Title, feedpost.Body, hours+' Hr Ago'));
                    }
                    else{
                        lstFinalChatterPost.add(new wrapChatterPost(feedpost.Title, feedpost.Body, minute+' Minutes Ago'));
                    }
                    system.debug('lstFinalChatterPost'+lstFinalChatterPost);
                }
            }
            lstDisplayPost.addAll(lstFinalChatterPost);
        }
        return lstDisplayPost;
        }
      return lstDisplayPost;
    }
    
    public void getSpecified(){
        lstDisplayPost.clear();
        for(wrapChatterPost specified: lstFinalChatterPost){
            if(specified.strTittle==strPostType){
                lstDisplayPost.add(specified);
            }
        }
    }
    public void getAll(){
        getAppointmentID();
        if(!SetAppID.isEmpty()){
           // getChatterPost();
        }
    }
    
    public void getBack(){
        lstDisplayPost.clear();
        lstDisplayPost.addAll(lstFinalChatterPost);
    }
    
    public class wrapChatterPost{
        public string strTittle {get; set;}
        public string strBody {get; set;}
        public string strDuration {get; set;}
        
        public wrapChatterPost(string Tittle, string Body, string Duration){
            strTittle = Tittle;
            strBody = Body;
            strDuration = Duration;
        }
    }
}