objects/App_Config__c.object
<CustomObject><fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <type>TextArea</type>
    </fields><customSettingsType>List</customSettingsType><description>Stores all configurable settings for USF</description><enableFeeds>false</enableFeeds><label>App Config</label><visibility>Public</visibility></CustomObject>

objects/AppointmentContact__c.object
<CustomObject><fields>
        <fullName>AppointmentSlot__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Appointment Slot</label>
        <referenceTo>Counsellor_Availability__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointment_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><fields>
        <fullName>CWID__c</fullName>
        <formula>Contact__r.CWID__c</formula>
        <label>CWID</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Center__c</fullName>
        <inlineHelpText>This field will get updated by the workflow on creation of the appointment</inlineHelpText>
        <label>Center</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Coach_Specialty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coach Specialty</label>
        <referenceTo>Specialty__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointment_Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Date_Time__c</fullName>
        <formula>AppointmentSlot__r.Start_Time__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date/Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Notes__c</fullName>
        <description>Notes provided by the student during appointment scheduling (LWC)</description>
        <label>Background Notes (Visible to Students)</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Reason_for_Meeting__c</fullName>
        <label>Appointment Reasons</label>
        <picklist>
            <picklistValues>
                <fullName>Academic Coaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Probation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Concerns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housing / Residence Hall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leave of Absence / Withdrawal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Concerns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major / Minor Exploration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Study Abroad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Student Survey</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields>
        <fullName>SelectedCourse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>hed__Course_Offering__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Staff__c</fullName>
        <description>Supports the email template functionality (CASA and LWCl)</description>
        <formula>AppointmentSlot__r.Coach_Full_Name__c</formula>
        <label>Staff</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Start_Time__c</fullName>
        <formula>IF(
  OR(
    VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) = 0,
    VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) = 12
  ),
  "12",
  TEXT( VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) 
   -
   IF( 
     VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) &lt; 12, 
     0, 
     12 
   ) 
  )
)
&amp; ":" &amp;
MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 15, 2 )
&amp; " " &amp;
IF(
  VALUE( MID( TEXT( AppointmentSlot__r.Start_Time__c - 7), 12, 2 ) ) &lt; 12,
  "AM",
  "PM"
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Time</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>175</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled by Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Appointments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Notes</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Strike__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Strike</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Appointment</label><nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Appointments</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Contact.object
<CustomObject><fields>
        <fullName>AcademicSuccessCoach__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Academic Success Coach</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notEqual</operation>
                <value>Customer Community User</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>CWID__c</fullName>
        <description>The primary USF ID</description>
        <externalId>true</externalId>
        <label>CWID</label>
        <length>100</length>
        <type>Text</type>
    </fields><fields>
        <fullName>No_of_Strikes_in_Writing_Center__c</fullName>
        <label>No of Strikes in Writing Center</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>No_of_strikes_in_Peer_Center__c</fullName>
        <label>No of Strikes in Peer Center</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Number_of_Units_in_Current_Term__c</fullName>
        <label>Number of Units in Current Term</label>
        <precision>3</precision>
        <scale>0</scale>
        
        <type>Number</type>
    </fields><fields>
        <fullName>Photo__c</fullName>
        <formula>IMAGE('https://artemis.usfca.edu:8030/'&amp; CWID__c &amp;'.JPG','Image Not Found', 100,100)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Photo</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Reason_Withdrawn__c</fullName>
        <label>Reason Withdrawn</label>
        <length>255</length>
        
        <type>Text</type>
    </fields><fields>
        <fullName>Special_Advisor__c</fullName>
        <label>Special Advisor</label>
        <length>175</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Staff__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to identify a member of USF Staff for integration purposes.</description>
        <label>Staff</label>
        <type>Checkbox</type>
    </fields><compactLayoutAssignment>hed__HEDA_Contact_Compact_Layout</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Counsellor_Availability__c.object
<CustomObject><fields>
        <fullName>Availability__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used to store the reference to Availability</description>
        <label>Availability</label>
        <referenceTo>Counselor_Availability_Definition__c</referenceTo>
        <relationshipLabel>Slots (Availability)</relationshipLabel>
        <relationshipName>Slots</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Center__c</fullName>
        <formula>Availability__r.Success_Center__r.Name</formula>
        <label>Center</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Notes__c</fullName>
        <description>Notes provided by the consultant</description>
        <label>Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields><fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>175</length>
        <required>true</required>
        <type>Text</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed by Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant Checked-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Appointments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Slot</label><nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Coach Availability Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Slots</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Counselor_Availability_Definition__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Availability</label><nameField>
        <displayFormat>CAD-{0000}</displayFormat>
        <label>Coach Availability Definition Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Availability</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Read</sharingModel></CustomObject>

objects/hed__Course_Offering__c.object
<CustomObject><fields>
        <fullName>hed__Term__c</fullName>
        <label>Term</label>
        <referenceTo>hed__Term__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Course_Offering_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Joins Courses and Terms to contain information related to a single occurrence of a course.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Course Offering</label><nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField><pluralLabel>Course Offerings</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/hed__Term__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Term_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Unit of time in which academic activities are taking place.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Term</label><nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Terms</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/Specialty__c.object
<CustomObject><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Specialty</label><nameField>
        <label>Specialty Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Specialties</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/USF_StudentDashboardExtn.cls
//************************************************************************************
// Name             : USF_StudentDashboardExtn
// Description      : Controller for USF_StudentDashboard Visualforce page
// Created By       : Mohan Kalagatla
// Created Date     : 08/30/2016
// ************************Version Updates********************************************
// Date             Developer           Description
// -----------------------------------------------------------------------------------
// 08/30/2016       Mohan Kalagatla       Created
// ************************************************************************************
//public with sharing class USF_StudentDashboardExtn{
//Change it to with sharing once security model is in place
public without sharing class USF_StudentDashboardExtn{
ApexPages.StandardController stdController {get; set;}
public Id contactId {get; set;}
public String cwid {get;set;}
public Contact contactRecord {get; set;}
public Id currentAppointmentId {get; set;}
public Boolean outsideLeadTime {get;set;}
public Id CASARecordTypeId {get; set;}
public Id LWCRecordTypeId {get; set;}
public List<hed__Course_Offering__c> coursesList{get; set;}
public String learningCenter{get; set;}
public String writingCenter{get; set;}
public String cancel {get; set;}
public String complete {get; set;}

//These variables are used for dashboard 
public Boolean isPermissionAssgined {get;set;}
public String userId {get; set;}

    // Constructor to perform initializations
    public USF_StudentDashboardExtn(ApexPages.StandardController controller){
      try{
            String usrProfileName = [select id, Profile.Name from User where id = :Userinfo.getUserId()].Profile.Name;     
            userId = UserInfo.getUserId();
            isPermissionAssgined =USF_PermissionSetAssignmentUtli.getPermissionSetFlag();         
            stdController = controller;
            Id loggedInUserContactId = [Select Id, ContactId FROM User where Id =: UserInfo.getUserId() LIMIT 1].ContactId;
            If(loggedInUserContactId != null){
            contactId = loggedInUserContactId;
            }
            else{
            contactId = ((Contact)stdController.getRecord()).Id;
            }
            
            contactRecord = [SELECT Id,Name,Photo__c,PhotoUrl,Department,CWID__c,Special_Advisor__c,AcademicSuccessCoach__c,
                             AcademicSuccessCoach__r.Department,AcademicSuccessCoach__r.Name,AcademicSuccessCoach__r.Email,
                             AcademicSuccessCoach__r.Phone
                             FROM Contact WHERE Id = :contactId LIMIT 1];  
            if(contactRecord != null) {
                cwid = contactRecord.CWID__c;
            }
            CASARecordTypeId = [SELECT Id,DeveloperName,SobjectType FROM RecordType WHERE SobjectType ='AppointmentContact__c' 
                            AND DeveloperName = :App_Config__c.getInstance('CASA Appointment RecordType').Text_Value__c LIMIT 1].Id;   
            LWCRecordTypeId = [SELECT Id,DeveloperName,SobjectType FROM RecordType WHERE SobjectType ='AppointmentContact__c' 
                            AND DeveloperName= :App_Config__c.getInstance('LWC Appointment RecordType').Text_Value__c LIMIT 1].Id;
                            
            learningCenter = App_Config__c.getInstance('Learning Center').Text_Value__c;
            writingCenter = App_Config__c.getInstance('Writing Center').Text_Value__c;
            cancel = App_Config__c.getInstance('Cancel').Text_Value__c;
            complete = App_Config__c.getInstance('Complete').Text_Value__c;
                       
            //Fetch courses for current term        
            Date todayDate = Date.today();
            List<hed__Term__c> termsList = USF_DBUtil.getTerm(todayDate,todayDate);
            if(!termsList.isEmpty()){
                hed__Term__c term = termsList[0];
                //coursesList = USF_DBUtil.getCoursesByTerm(term.Id); 
                coursesList = USF_DBUtil.getCoursesByContact(loggedInUserContactId);
                System.debug('**coursesList: '+coursesList);
            }
            outsideLeadTime = true;
        }
         catch(Exception ex){
                // Display the error message
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
           } 
    }
    
    //Get appointments
    public List<USF_AppointmentDTO> getappDTOList(){
        List<USF_AppointmentDTO> appDTOList = new List<USF_AppointmentDTO>();
        List<AppointmentContact__c> appointments = [SELECT Id,Name,RecordTypeId,AppointmentSlot__r.Start_Time__c,AppointmentSlot__r.End_Time__c,Staff__c,Location__c,Description__c,Date_Time__c,Status__c,Notes__c,SelectedCourse__r.Name,
                            Center__c,Reason_for_Meeting__c,Coach_Specialty__r.Name
                            FROM AppointmentContact__c
                            WHERE Contact__c = :contactId AND Date_Time__c > :System.now() ORDER BY Date_Time__c ASC];  
        
            if(appointments!=null && !appointments.isEmpty()){
                for(AppointmentContact__c app:appointments ){
                    //USF_AppointmentDTO appDTO = new USF_AppointmentDTO(app,app.Date_Time__c.format('EEEE,d MMM yy, h:mm a')); // DFCT0010899 
                    //Added by Vandana - DFCT0010943
                    String dateStr = app.Date_Time__c.format('MMMM d (EEE)')+'<br>'+app.AppointmentSlot__r.Start_Time__c.format('h:mm a')+' - '+app.AppointmentSlot__r.End_Time__c.format('h:mm a');
                    USF_AppointmentDTO appDTO = new USF_AppointmentDTO(app,dateStr.toUpperCase());
                    appDTOList.add(appDTO);
                } 
            }
            return appDTOList;
      }     
      
      // Method to verify lead time of cancellation 
      public void verifyLeadTime() {
        try{
        List<AppointmentContact__c> appointments = [Select Id,Date_Time__c,AppointmentSlot__c,AppointmentSlot__r.Availability__c,AppointmentSlot__r.Availability__r.Success_Center__c,
                                                    AppointmentSlot__r.Availability__r.Success_Center__r.LeadTime__c 
                                                    FROM AppointmentContact__c 
                                                    where Id =: currentAppointmentId];
        if(appointments.size() > 0) {
            Decimal leadTime = appointments[0].AppointmentSlot__r.Availability__r.Success_Center__r.LeadTime__c;
            System.debug('appointments[0]'+appointments[0]);
            System.debug('appointments[0].AppointmentSlot__c'+appointments[0].AppointmentSlot__c);
            System.debug('appointments[0].AppointmentSlot__r.Availability__c'+appointments[0].AppointmentSlot__r.Availability__c);
            System.debug('appointments[0].AppointmentSlot__r.Availability__r.Success_Center__c'+appointments[0].AppointmentSlot__r.Availability__r.Success_Center__c);
            Long timeNow = DateTime.now().getTime();//time since January 1,1970 GMT 
            Long appointmentTime = appointments[0].Date_Time__c.getTime();
            //Long myDate = Datetime.newInstance(2016, 8, 29, 14, 52, 0).getTime();
            Long milliseconds = appointmentTime - timeNow;
            Long minutes = milliseconds / (1000 * 60);
            if(minutes < (leadTime * 60)) {
                outsideLeadTime = false;
                //return outsideLeadTime;
            }
            else {
                outsideLeadTime = true;
                //return outsideLeadTime;
            }
        } 
        }
        catch(Exception ex){
                // Display the error message
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
        }     
    }
    
    // Cancel appointment
    public void cancelAppointment() {
    try {
        List<AppointmentContact__c> appointments = USF_DBUtil.getAppointment(currentAppointmentId);
        system.debug('appointments: '+appointments);
            if(appointments!=null && !appointments.isEmpty()){
                if(appointments[0] !=null && appointments[0].RecordTypeId == CASARecordTypeId && appointments[0].Status__c != App_Config__c.getInstance('CASA Appointment Cancelled Status').Text_Value__c){
                    appointments[0].Status__c = App_Config__c.getInstance('CASA Appointment Cancelled Status').Text_Value__c;    
                    update appointments[0];
                }
                else if(appointments[0]!=null && appointments[0].RecordTypeId == LWCRecordTypeId && appointments[0].Status__c != App_Config__c.getInstance('LWC Appointment CancelledbyStudent').Text_Value__c){
                    String centerId = appointments[0].AppointmentSlot__r.Availability__r.Success_Center__c;
                    List<User> currentUsers = [Select Id, ContactId FROM User where Id =: UserInfo.getUserId()];
                    system.debug('outsideLeadTime: '+outsideLeadTime);
                    if(outsideLeadTime == false) {
                        List<Profile> profiles = [Select Id,Name FROM Profile where Id =: UserInfo.getProfileId()];
                        if(profiles.size() > 0) {
                            if(profiles[0].Name == App_Config__c.getInstance('Student Profile').Text_Value__c || isPermissionAssgined){
                                if(appointments.size() > 0) {
                                    appointments[0].Status__c = App_Config__c.getInstance('LWC Appointment CancelledbyStudent').Text_Value__c;
                                    appointments[0].Strike__c = true;
                                    if(currentUsers[0].ContactId != null) {
                                        List<Contact> contacts = [Select Id,
                                                                    No_of_strikes_in_Writing_Center__c,
                                                                    No_of_strikes_in_Peer_Center__c 
                                                                    FROM Contact 
                                                                    where Id =: currentUsers[0].ContactId];
                                        if(appointments[0].Center__c.contains(App_Config__c.getInstance('Learning Center').Text_Value__c)) {
                                            if(contacts[0].No_of_strikes_in_Peer_Center__c >= 
                                               appointments[0].AppointmentSlot__r.Availability__r.Success_Center__r.Student_Missed_Per_Center__c) {
                                                cancelFutureAppts(centerId,currentUsers[0].ContactId);
                                            }
                                        }
                                        else if(appointments[0].Center__c.contains(App_Config__c.getInstance('Speaking Center').Text_Value__c)) {
                                            /*if(contacts[0].No_of_strikes_in_Speaking_Center__c >= 
                                               appointments[0].AppointmentSlot__r.Availability__r.Success_Center__r.Student_Missed_Per_Center__c) {
                                                cancelFutureAppts(centerId,currentUsers[0].ContactId);
                                            }*/
                                        }
                                        else if(appointments[0].Center__c.contains(App_Config__c.getInstance('Writing Center').Text_Value__c)) {
                                            if(contacts[0].No_of_strikes_in_Writing_Center__c >= 
                                               appointments[0].AppointmentSlot__r.Availability__r.Success_Center__r.Student_Missed_Per_Center__c) {
                                                cancelFutureAppts(centerId,currentUsers[0].ContactId);
                                            }
                                        }
                                    }
                                }
                            }
                            else{
                                if(appointments.size() > 0) {
                                    appointments[0].Status__c = App_Config__c.getInstance('LWC Appointment CancelledbyStudent').Text_Value__c;
                                }
                            }
                        }
                    }
                    else {
                        system.debug('appointmentsELSE: '+appointments[0]);
                        appointments[0].Status__c = App_Config__c.getInstance('LWC Appointment CancelledbyStudent').Text_Value__c;
                    }
                    if(appointments.size() > 0) {
                        update appointments[0];
                    }
                }
                }
        }   
        catch(Exception ex){
            // Display the error message
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
        }
    }
    
    // Method to cancel future appointments
    public void cancelFutureAppts(String centerId, Id contactId) {
    try{
        List<AppointmentContact__c> apptsToBeCancelled = [Select Id FROM AppointmentContact__c 
                                                            where Contact__c =:contactId
                                                            and AppointmentSlot__r.Availability__r.Success_Center__c =:centerId
                                                            And Status__c = :App_Config__c.getInstance('LWC Appointment Confirmed Status').Text_Value__c];
            if(apptsToBeCancelled.size() > 0) {
                for(AppointmentContact__c ac : apptsToBeCancelled) {
                    ac.Status__c = App_Config__c.getInstance('LWC Appointment CancelledbyStudent').Text_Value__c;
                }
                update apptsToBeCancelled;
            }
        }
        catch(Exception ex){
                // Display the error message
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
        }
    } 
    
      
}