objects/App_Config__c.object
<CustomObject><fields>
        <fullName>Text_Value__c</fullName>
        <label>Text Value</label>
        <type>TextArea</type>
    </fields><customSettingsType>List</customSettingsType><description>Stores all configurable settings for USF</description><enableFeeds>false</enableFeeds><label>App Config</label><visibility>Public</visibility></CustomObject>

objects/Case.object
<CustomObject><fields>
        <fullName>Areas_for_improvement__c</fullName>
        <description>This field holds the areas for improvement values in Reasons Section on EAP Report Form page.</description>
        <label>Areas for Improvement</label>
        <picklist>
            <picklistValues>
                <fullName>Attendance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Participation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Grades</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields>
        <fullName>CWID__c</fullName>
        <formula>Contact.CWID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CWID</label>
        <type>Text</type>
    </fields><fields>
        <fullName>ContactFirstName__c</fullName>
        <formula>Contact.FirstName</formula>
        <label>ContactFirstName</label>
        <type>Text</type>
    </fields><fields>
        <fullName>ContactLastName__c</fullName>
        <formula>Contact.LastName</formula>
        <label>ContactLastName</label>
        <type>Text</type>
    </fields><fields>
        <fullName>CourseName__c</fullName>
        <formula>Course_Offering__r.hed__Course__r.Name</formula>
        <label>Course Name</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Course_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>hed__Course_Offering__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Course_Section__c</fullName>
        <formula>Course_Offering__r.hed__Section_ID__c</formula>
        <label>Course Section</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Description</fullName>
        
    </fields><fields>
        <fullName>Estimated_Grade__c</fullName>
        <label>Estimated Grade</label>
        <length>175</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Faculty__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>EAP Faculty Referrer</description>
        <label>Faculty</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (Faculty)</relationshipLabel>
        <relationshipName>Cases_Faculty</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields><fields>
        <fullName>Origin</fullName>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit - Drop in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit - Scheduled Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WebTrack</fullName>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields>
        <fullName>OwnerId</fullName>
        
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Priority</fullName>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Reason</fullName>
        <picklist>
            <picklistValues>
                <fullName>Academic Coaching</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Disqualification</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Form Processing</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Integrity</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Probation</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Appointment Information</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>CMBIT</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Dean's Letter / Tuition Adjustment</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Disability Related Issues</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Disruptive Behavior</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Early Alert</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty/Student Complaint</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty Notification</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Needs</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Grade Appeal / Grade Change</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Graduation</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Homesickness</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Housing / Residence Hall</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Leave of Absence/Withdrawal from USF</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Loss / Grief</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Major / Minor Exploration</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Health</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>New Student Survey</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Referral</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Assistance</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>SOM Waitlist</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Study Abroad</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Substance Abuse</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Underenrolled</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields>
        <fullName>Recommendations__c</fullName>
        <description>This field holds the 'recommendation' values of Reasons Section on EAP Report Form page.</description>
        <label>Recommendations</label>
        <picklist>
            <picklistValues>
                <fullName>See Instructor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tutoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplemental Instruction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Counseling/Coaching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Disability Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Improve Study Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Writing Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consider Withdrawing from Course</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>See CASA Staff</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Status</fullName>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
                <closed>false</closed>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <closed>false</closed>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
                <closed>true</closed>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
                <closed>true</closed>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Subject</fullName>
        
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Type</fullName>
        <picklist>
            <picklistValues>
                <fullName>Problem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feature Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Question</fullName>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields>
        <fullName>Work__c</fullName>
        <description>This field holds the 'Work' values of Reasons Section on EAP Report Form page.</description>
        <label>Work</label>
        <picklist>
            <picklistValues>
                <fullName>Quality of work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Late Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lack of Study Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time Management Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lack of Motivation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performing below a "C"</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Contact.object
<CustomObject><fields>
        <fullName>CWID__c</fullName>
        <description>The primary USF ID</description>
        <externalId>true</externalId>
        <label>CWID</label>
        <length>100</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Faculty__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to identify a member of faculty for integration purposes.</description>
        <label>Faculty</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Number_of_Units_in_Current_Term__c</fullName>
        <label>Number of Units in Current Term</label>
        <precision>3</precision>
        <scale>0</scale>
        
        <type>Number</type>
    </fields><fields>
        <fullName>Reason_Withdrawn__c</fullName>
        <label>Reason Withdrawn</label>
        <length>255</length>
        
        <type>Text</type>
    </fields><compactLayoutAssignment>hed__HEDA_Contact_Compact_Layout</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/hed__Course__c.object
<CustomObject><fields>
        <fullName>Course_Number__c</fullName>
        <label>Course Number</label>
        <length>3</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Course_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Academic course that a Department or School (the degree-granting Account type for the University) offers.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Course</label><nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Courses</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/hed__Course_Offering__c.object
<CustomObject><fields>
        <fullName>hed__Section_ID__c</fullName>
        <label>Section ID</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>hed__Course__c</fullName>
        <label>Course</label>
        <referenceTo>hed__Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Course_Offering_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Joins Courses and Terms to contain information related to a single occurrence of a course.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Course Offering</label><nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField><pluralLabel>Course Offerings</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/USF_FacultyStaffEAPFormController.cls
/************************************************************************************
 Name             : USF_FacultyStaffEAPFormController 
 Description      : Controller for USF_FacultyStaffEAPForm Visualforce page
 Created By       : Manjunath Singh
 Created Date     : 09/09/2016
 ************************Version Updates********************************************
 Date             Developer           Description
 -----------------------------------------------------------------------------------
 09/09/2016       Manjunath Singh       Created
 ************************************************************************************/

public with sharing class USF_FacultyStaffEAPFormController {

    public Case newEAPReport{get;set;}
    public String sId;
    public String sName{get;set;}
    public String cId;
    public String ascId;
    public String caseId;
    public Boolean viewFormToggle {get;set;}
    public String facultyName{get;set;}
    public List<hed__Course_Offering__c> courseOffering;
    public String courseSectionName{get;set;}
    public String message {get;set;}
    public Case eapReportRecord {get;set;}
    private User loggedInUser;



  /***************************************************************************
    Description: This method is used for Areas for Improvement multiselect 
                 picklist to checkbox conversion
    Return type: String[]
    Parameters: None
    Created By: Manjunath Singh
    ***************************************************************************/
    
    public String[] areasOfImp=new String [] {};
    
    public String[] getareasOfImp() {
        return areasOfImp;
    }

    public void setareasOfImp(String[] areasOfImp) {
        this.areasOfImp= areasOfImp;
    }
    
    


  /***************************************************************************
    Description: This method is used for work multiselect 
                 picklist to checkbox conversion
    Return type: String[]
    Parameters: None
    Created By: Manjunath Singh
    ***************************************************************************/
    Public String[] selectedWork = new String[]{};
    
    public String[] getselectedWork() {
        return selectedWork;
    }

    public void setselectedWork(String[] selectedWork) {
        this.selectedWork = selectedWork;
    }
    

    
  /***************************************************************************
    Description: This method is used for recomendations multiselect 
                 picklist to checkbox conversion
    Return type: String[]
    Parameters: None
    Created By: Manjunath Singh
    ***************************************************************************/
    Public String[] selectedRecomendations = new String[]{};
    
    public String[] getselectedRecomendations () {
        return selectedRecomendations ;
    }

    public void setselectedRecomendations (String[] selectedRecomendations) {
        this.selectedRecomendations = selectedRecomendations;
    }

    /***************************************************************************
    Description: This is the consturtor.
    Return type: None
    Parameters: None
    Created By: Manjunath Singh
    ***************************************************************************/
    public USF_FacultyStaffEAPFormController(ApexPages.StandardController controller) {
    
    viewFormToggle=false;
    
    courseOffering=new List<hed__Course_Offering__c>();
    sId=Apexpages.currentPage().getParameters().get('sId');
    sName=Apexpages.currentPage().getParameters().get('sName');
    cId=Apexpages.currentPage().getParameters().get('cId');
    ascId=Apexpages.currentPage().getParameters().get('ascId');
    
    //This is for View form functionality-Start
    caseId=Apexpages.currentPage().getParameters().get('eapId');
    viewFormToggle=(Apexpages.currentPage().getParameters().get('view')!=null && Apexpages.currentPage().getParameters().get('view')!='')?true:false;
    loggedInUser=[Select id,contactid from User where id=:UserInfo.getUserId()];

    if(caseId!=null && caseId!='' && viewFormToggle){
          
          populateViewForm();
    }
    
    //This is for View form functionality-End
    
    facultyName=UserInfo.getName();
    
    
    //courseOffering=[SELECT id,hed__Course__r.name,hed__Section_ID__c,hed__Course__r.Course_Number__c from hed__Course_Offering__c where id=:cId LIMIT 1];
    courseOffering=USF_DBUtil.getCourseOfferingInfo(cId);
    if(courseOffering.size()!=0 && courseOffering!=null){
        if(courseOffering[0].hed__Section_ID__c != null)
            courseSectionName=courseOffering[0].hed__Course__r.name+ ' ('+courseOffering[0].hed__Section_ID__c +')';
        else
            courseSectionName=courseOffering[0].hed__Course__r.name;
    }
    
    Id devRecordTypeId = Schema.SObjectType.case.getRecordTypeInfosByName().get(App_Config__c.getInstance('EAP Report RecordType').Text_Value__c).getRecordTypeId();
    newEAPReport=(Case)controller.getRecord();
    if(ascId!=null && ascId!=''){
    newEAPReport.ownerId=ascId;
    }
    if(cId!=null && cId!=''){
    newEAPReport.Course_Offering__c=cId;
    }
    if(loggedInUser.contactid !=null){
    newEAPReport.Faculty__c=loggedInUser.contactId;
    }
    if(courseOffering!=null && courseOffering.size()>0)
    newEAPReport.subject=sName+' '+courseOffering[0].hed__Course__r.name+' '+courseOffering[0].hed__Course__r.Course_Number__c;
    newEAPReport.contactId=sId;
    newEAPReport.recordTypeId=devRecordTypeId;
    newEAPReport.Origin=App_Config__c.getInstance('EAP Form Referral value').Text_Value__c;
    newEAPReport.Reason=App_Config__c.getInstance('EAP Form Reason value').Text_Value__c;

    }
   /***************************************************************************
   Description: This method is used to save the submitted report. (Case)
   Return type: PageReference 
   Parameters: None
   Created By: Manjunath Singh
   ***************************************************************************/   
   public PageReference submitReferral(){

   try{
    if(areasOfImp !=null){
        for(String areaOfImprovement : areasOfImp ){
                                if(newEAPReport.Areas_for_improvement__c == null || newEAPReport.Areas_for_improvement__c == '')
                                    newEAPReport.Areas_for_improvement__c = areaOfImprovement + ';';
        
                                 else
                                    newEAPReport.Areas_for_improvement__c = newEAPReport.Areas_for_improvement__c + areaOfImprovement + ';';
                            } 
         }
     
    if(selectedWork !=null ){
        for(String work: selectedWork ){
                                if(newEAPReport.Work__c == null || newEAPReport.Work__c == '')
                                    newEAPReport.work__c = work+ ';';
        
                                 else
                                    newEAPReport.work__c = newEAPReport.work__c + work+ ';';
                            } 
    }
    
    if(selectedRecomendations !=null ){
        for(String recommendation: selectedRecomendations ){
                                if(newEAPReport.Recommendations__c == null || newEAPReport.Recommendations__c == '')
                                    newEAPReport.Recommendations__c = recommendation+ ';';
        
                                 else
                                    newEAPReport.Recommendations__c = newEAPReport.Recommendations__c + recommendation+ ';';
                            } 
    }
        if(newEAPReport != null){
            //insert newEAPReport;
            USF_DBUtil.insertEAPReport(newEAPReport);
        }
        message=App_Config__c.getInstance('EAP Form Submit Success Message').Text_Value__c;
    }
    catch(Exception e){
    message=e.getMessage();
    //Apexpages.addmessage(new ApexPages.message(ApexPages.severity.Error,e.getMessage()));
    }

return null;
}

 /*********************************************************************************
    Description: This method is is used to populate areas of improvment checkboxes.
    Return type: List<SelectOption>
    Parameters: None
    Created By: Manjunath Singh
    ******************************************************************************/

 public List<SelectOption> getAreasOfImprovement()
    {
       List<SelectOption> options = new List<SelectOption>();
            
       Schema.DescribeFieldResult fieldResult =case.Areas_for_improvement__c.getDescribe();
       
       List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            
       for( Schema.PicklistEntry f : ple)
       {
          options.add(new SelectOption(f.getLabel(), f.getValue()));
       }       
       return options;
    }
    
    
 /*********************************************************************************
    Description: This method is is used to populate work checkboxes.
    Return type: List<SelectOption>
    Parameters: None
    Created By: Manjunath Singh
    ******************************************************************************/
    
    public List<SelectOption> getWorkValues()
    {
       List<SelectOption> options = new List<SelectOption>();
            
       Schema.DescribeFieldResult fieldResult =case.Work__c.getDescribe();
       
       List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            
       for( Schema.PicklistEntry f : ple)
       {
          options.add(new SelectOption(f.getLabel(), f.getValue()));
       }       
       return options;
    }
    
    
 /*********************************************************************************
    Description: This method is is used to populate recommendations checkboxes.
    Return type: List<SelectOption>
    Parameters: None
    Created By: Manjunath Singh
    ******************************************************************************/
    
    public List<SelectOption> getRecommendationValues()
    {
      List<SelectOption> options = new List<SelectOption>();
            
       Schema.DescribeFieldResult fieldResult =case.Recommendations__c.getDescribe();
       
       List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            
       for( Schema.PicklistEntry f : ple)
       {
          options.add(new SelectOption(f.getLabel(), f.getValue()));
       }       
       return options;
    }
    
    
   /*******************************************************************************
    Description: This method is is used to populate form details in Read only mode.
    Return type: Void
    Parameters: None
    Created By: Manjunath Singh
    ******************************************************************************/
    
    public void populateViewForm(){
    
    try{
        eapReportRecord=[Select id,contact.name,CaseNumber,ContactLastName__c,ContactFirstName__c,Notes__c,CWID__c,CourseName__c,Course_Section__c, Areas_for_improvement__c,work__c,Recommendations__c,Description,Estimated_Grade__c from case where id=:caseId limit 1];
        areasOfImp=(eapReportRecord.Areas_for_improvement__c!=null && eapReportRecord.Areas_for_improvement__c!='')?eapReportRecord.Areas_for_improvement__c.split(';'):new string[]{};
        selectedWork=(eapReportRecord.work__c!=null && eapReportRecord.work__c!='')?eapReportRecord.work__c.split(';'):new string[]{};
        selectedRecomendations=(eapReportRecord.Recommendations__c!=null && eapReportRecord.Recommendations__c!='')?eapReportRecord.Recommendations__c.split(';'):new string[]{};
    }
    Catch(Exception e){
    
    }
    
    
    
    }

}