objects/Case.object
<CustomObject><fields>
        <fullName>Course_Connection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Connection</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>hed__Course_Enrollment__c.hed__Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.ContactId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>hed__Course_Enrollment__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Course_Name__c</fullName>
        <label>Course Name</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Description</fullName>
        
    </fields><fields>
        <fullName>Origin</fullName>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit - Drop in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit - Scheduled Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WebTrack</fullName>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields>
        <fullName>OwnerId</fullName>
        
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Priority</fullName>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Reason</fullName>
        <picklist>
            <picklistValues>
                <fullName>Academic Coaching</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Disqualification</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Form Processing</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Integrity</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Probation</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Appointment Information</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>CMBIT</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Dean's Letter / Tuition Adjustment</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Disability Related Issues</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Disruptive Behavior</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Early Alert</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty/Student Complaint</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty Notification</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Needs</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Grade Appeal / Grade Change</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Graduation</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Homesickness</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Housing / Residence Hall</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Leave of Absence/Withdrawal from USF</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Loss / Grief</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Major / Minor Exploration</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Health</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>New Student Survey</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Referral</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Assistance</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>SOM Waitlist</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Study Abroad</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Substance Abuse</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
            <picklistValues>
                <fullName>Underenrolled</fullName>
                <cssExposed>false</cssExposed>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Status</fullName>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
                <closed>false</closed>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <closed>false</closed>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
                <closed>true</closed>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
                <closed>true</closed>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Subject</fullName>
        
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Type</fullName>
        <picklist>
            <picklistValues>
                <fullName>Problem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feature Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Question</fullName>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>Private</sharingModel></CustomObject>

objects/hed__Course_Enrollment__c.object
<CustomObject><fields>
        <fullName>Course_Name__c</fullName>
        <formula>hed__Course_Offering__r.hed__Course__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Course Name</label>
        <type>Text</type>
    </fields><fields>
        <fullName>hed__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The student taking the course.</description>
        <inlineHelpText>The student taking the course.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Connections</relationshipLabel>
        <relationshipName>Student_Course_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Course_Enrollment_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Represents a connection to a Course Offering.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Course Connection</label><nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Course Connection ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Course Connections</pluralLabel><sharingModel>Read</sharingModel></CustomObject>

classes/CaseTutorRequestExtension.cls
public without sharing class CaseTutorRequestExtension {
    
    Static Id userContactId;
    
    public List<selectOption> courseConnection {
        
        get {
            // Get ContactId from User
            List<user> lstUser = [Select ContactId From User Where Id =: UserInfo.getUserId()];
            userContactId = lstUser[0].ContactId;
            
            // Get Course
            List<selectOption> courses = new List<selectOption>();
            courses.add(new selectOption('', '- None -'));
            for (hed__Course_Enrollment__c cc : [select id, Course_Name__c, hed__Contact__c from hed__Course_Enrollment__c where hed__Contact__c =: userContactId limit 100]) {
                courses.add(new selectOption(cc.id, cc.Course_Name__c));
            }
            return courses;
    
        }
        private set;
        
    }
   
    public String CourseSelected {get; set;}
        
    public Case cs;
    
    public CaseTutorRequestExtension(ApexPages.StandardController stdController){
        
        // Get ContactId from User
        //List<user> lstUser = [Select ContactId From User Where Id =: UserInfo.getUserId()];
        //userContactId = lstUser[0].ContactId;
            
        this.cs = (Case)stdController.getRecord();
        
    }
    
    public PageReference save(){
            
        Pagereference p = apexpages.Currentpage();
        PageReference pageRef = new PageReference('/USF_TutorRequestConfirmation');
        pageRef.setRedirect(true);
        
        // Set auto fields here
        cs.RecordtypeId = Label.Tutor_Request_Record_Type_Id;
        cs.Reason = 'Tutor Request';
        cs.Subject = 'Tutor Request';
        cs.Origin = 'Portal';  // Required
        cs.course_connection__c = CourseSelected;
        
        
        // Set Validation for Save with ContactId
            try {
                //system.debug('userContactId 2: ' + userContactId);
                
                //integer maxCount = database.countQuery('Select count() from Case where (contactId =: userContactId ) and ((status = \'New\') or (status = \'Open\')) ');
                //integer subjectCount = database.countQuery('Select count() from Case where (contactId =: userContactId) and ((status = \'New\') or (status = \'Open\')) and (course_connection__c =: CourseSelected )');
                
                integer maxCount = database.countQuery('Select count() from Case where (contactId =: userContactId ) and (isClosed = false) ');
                integer subjectCount = database.countQuery('Select count() from Case where (contactId =: userContactId) and (isClosed = false) and (course_connection__c =: CourseSelected )');
               
                if (maxCount >= 3) {
                    ApexPages.Message msg = new Apexpages.Message(ApexPages.severity.Info,'You have reached maximum number of request!');
                    ApexPages.addmessage(msg);
                    return p; 
                } else if (subjectCount >= 1) {
                    ApexPages.Message msg2 = new Apexpages.Message(ApexPages.severity.Info,'You have already requested tutor for this subject!');
                    ApexPages.addmessage(msg2);
                    return p; 
                } else {
                    try {
                        upsert cs;
                        return pageRef;
                    } catch(Exception ex) {
                        ApexPages.addMessages(ex);
                    }    
                }
            } catch(Exception ex) {
                ApexPages.addMessages(ex);
            }
        
        return null;
    }
    
    public PageReference cancel() {
       
        //system.debug('Cancel method');
        
        //PageReference pageRef = new PageReference(ApexPages.currentPage().getUrl());
        PageReference pageRef = new PageReference('/USF_StudentDashboard');
        pageRef.setRedirect(true);
        return pageRef;
    } 
       
}