objects/Contact.object
<CustomObject><fields>
        <fullName>AcademicSuccessCoach__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Academic Success Coach</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notEqual</operation>
                <value>Customer Community User</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>CWID__c</fullName>
        <description>The primary USF ID</description>
        <externalId>true</externalId>
        <label>CWID</label>
        <length>100</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Number_of_Units_in_Current_Term__c</fullName>
        <label>Number of Units in Current Term</label>
        <precision>3</precision>
        <scale>0</scale>
        
        <type>Number</type>
    </fields><fields>
        <fullName>Reason_Withdrawn__c</fullName>
        <label>Reason Withdrawn</label>
        <length>255</length>
        
        <type>Text</type>
    </fields><fields>
        <fullName>Student__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Related to Interaction functionality</description>
        <label>Student</label>
        <type>Checkbox</type>
    </fields><compactLayoutAssignment>hed__HEDA_Contact_Compact_Layout</compactLayoutAssignment><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/hed__Course__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Course_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Academic course that a Department or School (the degree-granting Account type for the University) offers.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Course</label><nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Courses</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/hed__Course_Enrollment__c.object
<CustomObject><fields>
        <fullName>hed__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The student taking the course.</description>
        <inlineHelpText>The student taking the course.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Connections</relationshipLabel>
        <relationshipName>Student_Course_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>hed__Course_Offering__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Course Offering the student is enrolled in. It's a Course offered at a specific Term.</description>
        <inlineHelpText>The Course Offering the student is enrolled in. It's a Course offered at a specific Term.</inlineHelpText>
        <label>Course Offering ID</label>
        <referenceTo>hed__Course_Offering__c</referenceTo>
        <relationshipLabel>Course Connection</relationshipLabel>
        <relationshipName>Course_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Course_Enrollment_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Represents a connection to a Course Offering.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Course Connection</label><nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Course Connection ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Course Connections</pluralLabel><sharingModel>Read</sharingModel></CustomObject>

objects/hed__Course_Offering__c.object
<CustomObject><fields>
        <fullName>hed__Section_ID__c</fullName>
        <label>Section ID</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>hed__Faculty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Faculty</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Courses_Taught</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>hed__Course__c</fullName>
        <label>Course</label>
        <referenceTo>hed__Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Course_Offering_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Joins Courses and Terms to contain information related to a single occurrence of a course.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Course Offering</label><nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField><pluralLabel>Course Offerings</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/USF_EAPReportController.cls
/************************************************************************************
// Name             : USF_EAPReportController
// Description      : Controller for USF_FacultyStaffEAPIntg Visualforce page
// Created By       : Manjunath Singh
// Created Date     : 08/30/2016
// ************************Version Updates********************************************
// Date             Developer           Description
// -----------------------------------------------------------------------------------
// 08/30/2016       Manjunath Singh       Created
// ************************************************************************************/
public with sharing class USF_EAPReportController{

    private User loggedInUser;
    public Integer pageSize{get;set;}
    public Integer studentPageSize{get;set;}
    public Integer noOfRecords{get; set;}
    public String courseOfferingId {get;set;}
    public boolean showStudentSection{get;set;}
    public Integer noOfStudentRecords{get; set;}
    public String courseName {get;set;}
 
    //Variable to store course records
    public ApexPages.StandardSetController coursesRecords;
    
    //Variable to store Student records
    public ApexPages.StandardSetController studentRecords;

    //Constructor
    public USF_EAPReportController(){
    
        pageSize=5;
        studentPageSize=5;
        showStudentSection=false;
        //selectedStudent='';
        loggedInUser=[Select id,contactid from User where id=:UserInfo.getUserId()];
        /*coursesRecords= new ApexPages.StandardSetController(Database.getQueryLocator(
                [SELECT id,name,hed__Course__r.name,hed__Section_ID__c FROM hed__Course_Offering__c WHERE hed__Faculty__c=:loggedInUser.contactId LIMIT 10000])
                );
                */
        coursesRecords=USF_DBUtil.getCourseOfferings(loggedInUser.contactId);       
        coursesRecords.setpageSize(pageSize);
        noOfRecords = coursesRecords.getResultSize();
        
    }

    public List<hed__Course_Offering__c> getCourses() {
        return (List<hed__Course_Offering__c>) coursesRecords.getRecords();
    }
    
    //Pagination methods for Courses
    public Boolean hasNext {
        get {
            return coursesRecords.getHasNext();
        }
        set;
    }
    public Boolean hasPrevious {
        get {
            return coursesRecords.getHasPrevious();
        }
        set;
    }
  
    public Integer pageNumber {
        get {
            return coursesRecords.getPageNumber();
        }
        set;
    }
  
    public void first() {
        coursesRecords.first();
    }
  
    public void last() {
        coursesRecords.last();
    }
  
    public void previous() {
        coursesRecords.previous();
    }
  
    public void next() {
        coursesRecords.next();    
    }
    
    
    public void viewStudents(){
    
   /* studentRecords= new ApexPages.StandardSetController(Database.getQueryLocator(
                [SELECT id,name,lastname,firstname,AcademicSuccessCoach__r.name,CWID__c FROM contact WHERE Student__c=true
                AND ID in(SELECT hed__Contact__c FROM hed__Course_Enrollment__c WHERE hed__Course_Offering__c=:courseOfferingId) ORDER BY lastname LIMIT 10000])
                );
                */
   studentRecords= USF_DBUtil.getStudentsForCourseOffering(courseOfferingId);            
    //if(studentRecords.getResultSize()>0){showStudentSection=true;}
    showStudentSection=true;
    studentRecords.setPageSize(studentPageSize);
    noOfStudentRecords=studentRecords.getResultSize();
    }
    
    public List<contact> getStudents() {
        return (List<contact>) studentRecords.getRecords();
    }
    
    //Pagination methods for Students
    public Boolean studentHasNext {
        get {
            return studentRecords.getHasNext();
        }
        set;
    }
    public Boolean studentHasPrevious {
        get {
            return studentRecords.getHasPrevious();
        }
        set;
    }
  
    public Integer studentPageNumber {
        get {
            return studentRecords.getPageNumber();
        }
        set;
    }
  
    public void studentFirst() {
        studentRecords.first();
    }
  
    public void studentLast() {
        studentRecords.last();
    }
  
    public void studentPrevious() {
        studentRecords.previous();
    }
  
    public void studentNext() {
        studentRecords.next();    
    }

}