objects/Counsellor_Availability__c.object
<CustomObject><fields>
        <fullName>Availability__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used to store the reference to Availability</description>
        <label>Availability</label>
        <referenceTo>Counselor_Availability_Definition__c</referenceTo>
        <relationshipLabel>Slots (Availability)</relationshipLabel>
        <relationshipName>Slots</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Coach_First_Name__c</fullName>
        <formula>Availability__r.Coach__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Coach First Name</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Coach_Last_Name__c</fullName>
        <formula>Availability__r.Coach__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Coach Last Name</label>
        <type>Text</type>
    </fields><fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Selected_Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Selected Course</label>
        <referenceTo>hed__Course_Offering__c</referenceTo>
        <relationshipLabel>Slots</relationshipLabel>
        <relationshipName>Slots</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields><allowInChatterGroups>true</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Slot</label><nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Coach Availability Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Slots</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Private</sharingModel></CustomObject>

objects/Counselor_Availability_Definition__c.object
<CustomObject><fields>
        <fullName>Success_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Center</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Center__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Availability (Center)</relationshipLabel>
        <relationshipName>Availability</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Availability</label><nameField>
        <displayFormat>CAD-{0000}</displayFormat>
        <label>Coach Availability Definition Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Availability</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Read</sharingModel></CustomObject>

classes/TestClass_Rit.cls
public class TestClass_Rit {
   
 /*
 *  @author     :   R. Mukherjee
 *  @date       :   4th August, 2016
 *  @param      :   Department,Date
 *  @purpose    :   Fetch CASA spesific details
 */ 
    public static List<Counsellor_Availability__c> getCA_CASA(String department, Date d){
        System.Debug('#Search Criteria  #   Date:'+d +',Deaprtment:'+department);
        List<Counsellor_Availability__c> slots=[
            Select  Id,
                    Selected_Course__c,
                    Coach_First_Name__c, 
                    Coach_Last_Name__c,
                    Start_Time__c, 
                    End_Time__c,
                    
                    Availability__r.Success_Center__r.Name
            from Counsellor_Availability__c
            where   Availability__r.Success_Center__r.Name = :department and 
                    DAY_Only(Start_Time__c) > :d and   
                    DAY_Only(Start_Time__c) <=:(d.addDays(15))                                          
                                                         ];
                
        return slots;
    }
    
    /*
 *  @author     :   R. Mukherjee
 *  @date       :   3rd August, 2016
 *  @param      :   Department,Centre,Course,Date
 *  @purpose    :   Fetch LWC spesific details
 * 
 */ 
     public static List<Counsellor_Availability__c> getCA_LWC(String department,String center,String course, Date d){
         
         
        System.Debug('#Search Criteria  #   Date:'+d +',Deaprtment:'+department+',Centre:'+center+',Course:'+course);
         
         if(course!=null){
             
             List<Counsellor_Availability__c>  slots=[
            
                    Select  Id,
                            Selected_Course__c,
                            Coach_First_Name__c, 
                            Coach_Last_Name__c,
                            Start_Time__c, 
                            End_Time__c,
                            
                            Availability__r.Success_Center__r.Name
                            
                    from Counsellor_Availability__c
                    where   
                            Availability__r.Success_Center__r.Name = :center and
                            //Availability__r.Course__c = :course and
                            DAY_Only(Start_Time__c) > :d and   
                            DAY_Only(Start_Time__c) <=:(d.addDays(15))                                          
                
                                                                 ];
             return slots;
         }
         else{
            
             List<Counsellor_Availability__c>  slots=[
            
                    Select  Id,
                            Selected_Course__c,
                            Coach_First_Name__c, 
                            Coach_Last_Name__c,
                            Start_Time__c, 
                            End_Time__c,
                            
                            Availability__r.Success_Center__r.Name
                    from Counsellor_Availability__c
                    where   
                            Availability__r.Success_Center__r.Name = :center and
                            DAY_Only(Start_Time__c) > :d and   
                            DAY_Only(Start_Time__c) <=:(d.addDays(15))                                          
                
                                                                 ];
             return slots;
             
         }
   
        
        
    }
    
    
/*
 *  @author     :   R. Mukherjee
 *  @date       :   4th August, 2016
 *  @purpose    :   Fetch  CASA/LWC spesific details according to paremeter 
 */  
      public static List<Counsellor_Availability__c> getCA(String department,String center, Date d){
        
        List<Counsellor_Availability__c> coaches=[
            
    Select  Id,
            Selected_Course__c,
            Coach_First_Name__c, 
            Coach_Last_Name__c,
            Start_Time__c, 
            End_Time__c,
            
            Availability__r.Success_Center__r.Name
    from Counsellor_Availability__c
    where   
           Availability__r.Success_Center__r.Name = :center and
            DAY_Only(Start_Time__c) > :d and   
            DAY_Only(Start_Time__c) <=:(d.addDays(15))                                          

                                                 ];  
        return coaches;
    }
    
}