objects/Counselor_Availability_Definition__c.object
<CustomObject><fields>
        <fullName>End_Date_Time__c</fullName>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>LWC, Cowell 215</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cowell 212</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC, Malloy 103</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>McLaren 107</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gleeson Library</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Front Desk Online/Canvas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UC 3rd Floor Lounge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UC 4th Floor Lounge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UC 5th Floor Lounge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hayes-Healy Formal Lounge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gillson Lounge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fromm Lounge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outtakes Cafe (LoMo by OneCard Office)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crossroads Cafe outside Bookstore Entrance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harney 512</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cowell 417/418</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kalmanovitz 309 Library</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>University Center, 3rd floor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pleasanton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>San Jose</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sacramento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downtown SF</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Max_No_Of_Slots__c</fullName>
        <label>Maximum No Of Slots/Day</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monday</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Repeat__c</fullName>
        <inlineHelpText>Select "Only Once" to create slots for a single day.
Select "Daily" to create slots every day of a specified date range. Do not select specific days.
Select "Weekly" to create slots for selected days of a specified date range. Select the specific days.</inlineHelpText>
        <label>Repeat</label>
        <picklist>
            <picklistValues>
                <fullName>Only Once</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Availability</label><nameField>
        <displayFormat>CAD-{0000}</displayFormat>
        <label>Coach Availability Definition Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Availability</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>Read</sharingModel></CustomObject>

classes/TestAvailabilityDefinitionCreation.cls
/******************************************************************************************************************************************
Apex Class Name     : TestAvailabilityDefinitionCreation
Version             : 1.0
Created Date        : 11 AUG 2016
Function            : Test class containing for Unit Testing
Modification Date   : 
Modified By         : Ritam Mukherjee
Modification Log    : 

**********************************************************************************************************************************************/




@isTest
public class TestAvailabilityDefinitionCreation {
    
    
     /* Method name : createAvailabilityDefinitionOnlyOnce
     * Purpose      : Test when trigger fire for creates coach availability slot records for Repeat = "Only Once"
     * Return Type  : Void
     * Mapping      : USF_CoachAvailabilityUtils.createOnlyOnceAvailabilitySlots(List<Counselor_Availability_Definition__c> nonRecurList)
     * Created on   : 11 AUG 2016 by Ritam Mukherjee
     */
    
    @isTest
    static void createAvailabilityDefinitionOnlyOnce(){
        Counselor_Availability_Definition__c cad_success=new Counselor_Availability_Definition__c(
        Start_Date_Time__c= Datetime.newInstance(2016,8,15,8,10,10),
        End_Date_Time__c= Datetime.newInstance(2016,8,15,10,10,10),
        Location__c='New York',
        
        Max_No_Of_Slots__c=2,
        Repeat__c='Only Once'
        
        );
        
        Counselor_Availability_Definition__c cad_failure=new Counselor_Availability_Definition__c(
        Start_Date_Time__c= Datetime.newInstance(2016,8,16,8,10,10),
        End_Date_Time__c= Datetime.newInstance(2016,8,15,10,10,10),
        Location__c='New York',
        
        Max_No_Of_Slots__c=2,
        Repeat__c='Only Once'
        
        );
        
        Test.startTest();
        Database.SaveResult result_success; 
        Database.SaveResult result_failure;
        Exception except;
        try
            {
                 result_success=Database.insert(cad_success);
                    result_failure=Database.insert(cad_failure);
            }
            catch(Exception ee)
            {
                except=ee.getCause();
                System.debug(ee);
            }
        
        Test.stopTest();
        
         System.assertEquals(result_success.isSuccess(),true);
         System.assertEquals(result_failure,null);
            
    }
    
  /* Method name    : createAvailabilityDefinitionDaily
     * Purpose      : Test when trigger fire for creates coach availability slot records for Repeat = "Daily"
     * Return Type  : Void
     * Mapping      : USF_CoachAvailabilityUtils.createWeeklyAvailabilitySlots(List<Counselor_Availability_Definition__c> weeklyRecList)
     * Created on   : 11 AUG 2016 by Ritam Mukherjee
     */
    
      @isTest
    static void createAvailabilityDefinitionDaily(){
        Counselor_Availability_Definition__c cad=new Counselor_Availability_Definition__c(
        Start_Date_Time__c= Datetime.newInstance(2016,8,15,8,10,10),
        End_Date_Time__c= Datetime.newInstance(2016,10,16,10,10,10),
        Location__c='New York',
        
        Max_No_Of_Slots__c=2,
        Repeat__c='Daily'
        
        );
        
        Test.startTest();
        Database.SaveResult result;  
        try
            {
                 result=Database.insert(cad);
            }
            catch(Exception ee)
            {
                System.debug(ee);
            }
        
        Test.stopTest();
        
         System.assertEquals(result.isSuccess(),true);
            
    }
    
     /* Method name : createAvailabilityDefinitionWeekly
     * Purpose      : Test when trigger fire for creates coach availability slot records for Repeat = "Only Once"
     * Return Type  : Void
     * Mapping      : USF_CoachAvailabilityUtils.createWeeklyAvailabilitySlots(List<Counselor_Availability_Definition__c> nonRecurList)
     * Created on   : 12 AUG 2016 by Ritam Mukherjee
     */
      @isTest
    static void createAvailabilityDefinitionWeekly(){
        Counselor_Availability_Definition__c cad=new Counselor_Availability_Definition__c(
        Start_Date_Time__c= Datetime.newInstance(2016,8,15,8,10,10),
        End_Date_Time__c= Datetime.newInstance(2016,8,16,10,10,10),
        Location__c='New York',
        
        Max_No_Of_Slots__c=2,
        Repeat__c='Weekly',
        Monday__c = true,
        Wednesday__c = true
        
        );
        
        Test.startTest();
        Database.SaveResult result;  
        try
            {
                 result=Database.insert(cad);
            }
            catch(Exception ee)
            {
                System.debug(ee);
            }
        
        Test.stopTest();
        
         System.assertEquals(result.isSuccess(),true);
            
    }
 
 @isTest
    static void createAvailabilityDefinitionOnlyOnce_exceptional() {
     
        
        Counselor_Availability_Definition__c cad_failure=new Counselor_Availability_Definition__c(
        Start_Date_Time__c= Datetime.newInstance(2016,8,16,8,10,10),
        End_Date_Time__c= Datetime.newInstance(2016,8,15,10,10,10),
        Location__c='New York',
        
        Max_No_Of_Slots__c=0,
        Repeat__c='Only Once'
        
        );
        
        Test.startTest();
        Database.SaveResult result; 
        try
        {
            result=Database.insert(cad_failure);
            
        }catch(Exception e){
            System.debug('Exception :   '+e);
        }
        Test.stopTest();
        
        

         
            
    }
}