objects/hed__Course__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Course_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Academic course that a Department or School (the degree-granting Account type for the University) offers.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Course</label><nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Courses</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/hed__Course_Offering__c.object
<CustomObject><fields>
        <fullName>hed__Term__c</fullName>
        <label>Term</label>
        <referenceTo>hed__Term__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields><fields>
        <fullName>hed__Course__c</fullName>
        <label>Course</label>
        <referenceTo>hed__Course__c</referenceTo>
        <relationshipLabel>Course Offerings</relationshipLabel>
        <relationshipName>Course_Offerings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Course_Offering_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Joins Courses and Terms to contain information related to a single occurrence of a course.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Course Offering</label><nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField><pluralLabel>Course Offerings</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/hed__Term__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>hed__HEDA_Term_Compact_Layout</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><deprecated>false</deprecated><description>Unit of time in which academic activities are taking place.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Term</label><nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Terms</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

classes/USF_EAPReportControllerTest.cls
/** Class Name   : USF_EAPReportControllerTest
 *  Description  : Test Class for USF_EAPReportControllerClass
 *  Created By   : Ankit Jain
 *  Created On   : 27-Sep-2016
 *  Modification Log:
   ------------------------------------------------------------------------------------
   Developer                       Date                Description
   ------------------------------------------------------------------------------------
   Ankit Jain                     27-Sep-2016          Original Version
 */
@isTest
public with sharing class USF_EAPReportControllerTest{
    @isTest
    static void testUSF_EAPReportController(){
        /*UserRole ur = Test_Utility.createRole();
        insert ur;*/
        User usr = Test_Utility.createTestUser('testAdmin','System Administrator');
        if(usr!=null)
            insert usr;
        hed__Course_Offering__c courseOffering; 
        hed__Course__c course;   
        System.runAs(usr){           
            Account acc = Test_Utility.createAccount();
            if(acc!=null)
                insert acc;    
            List<Contact> conList = Test_Utility.createContact(1,usr.id,true,acc.id);
            if(conList!=null && conList.size()>0)
                insert conList;   
            course = Test_Utility.createCourse(acc.id);
            if(course!=null)
               insert course;
            hed__Term__c term = Test_Utility.createTerm(acc.id);
            if(term!=null)
                insert term; 
       
        
            courseOffering = Test_Utility.createCourseOffering(course.id,term.id);   
        
            if(courseOffering != null)
                insert courseOffering;
        
            Test.startTest();
            USF_EAPReportController rc = new USF_EAPReportController();
            List<hed__Course_Offering__c> coList= rc.getCourses();
            System.assertEquals(coList.size(),1);
            rc.first();
            rc.last();
            rc.previous();
            rc.next();
            Boolean hasPrevious = rc.hasPrevious;
            Boolean hasNext = rc.hasNext; 
            Integer pgNumber = rc.pageNumber;
            rc.viewStudents();
            List<contact> stuList = rc.getStudents();
            rc.studentfirst();
            rc.studentlast();
            rc.studentprevious();
            rc.studentnext();
            Boolean studenthasPrevious = rc.studenthasPrevious;
            Boolean studenthasNext = rc.studenthasNext; 
            Integer studentpgNumber = rc.studentpageNumber;
            rc.courseName = course.Name+'-'+courseOffering.Name;
            Test.stopTest();        
        } 
          
    }
    
}